export type CompanyCategory =
  | "telekommunikation"
  | "versicherung"
  | "energie"
  | "fitness"
  | "streaming"
  | "bank"
  | "internet"
  | "mobilfunk"
  | "verlag"
  | "mitgliedschaft"
  | "arbeit"
  | "sonstiges"

export interface Company {
  id: string
  name: string
  category: CompanyCategory
  address: string
  kuendigungsfrist: string
  mindestlaufzeit: string
  kuendigungsart: string[]
  hinweise: string
}

export const CATEGORY_LABELS: Record<CompanyCategory, string> = {
  telekommunikation: "Telekommunikation",
  versicherung: "Versicherung",
  energie: "Energie",
  fitness: "Fitness & Sport",
  streaming: "Streaming & Medien",
  bank: "Bank & Finanzen",
  internet: "Internet & DSL",
  mobilfunk: "Mobilfunk",
  verlag: "Verlag & Zeitschriften",
  mitgliedschaft: "Mitgliedschaft & Verein",
  arbeit: "Job & Karriere",
  sonstiges: "Sonstiges",
}

export const companies: Company[] = [
  // ========== TELEKOMMUNIKATION ==========
  {
    id: "telekom",
    name: "Deutsche Telekom",
    category: "telekommunikation",
    address: "Telekom Deutschland GmbH\nKundenservice\n53171 Bonn",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online-Kuendigung ueber das Kundencenter moeglich.",
  },
  {
    id: "vodafone",
    name: "Vodafone",
    category: "telekommunikation",
    address: "Vodafone GmbH\nKundenbetreuung\n40549 Duesseldorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Fax", "Online"],
    hinweise: "Fax: 0211 533 1612. Online-Kuendigung ueber MeinVodafone.",
  },
  {
    id: "o2",
    name: "O2 / Telefonica",
    category: "telekommunikation",
    address: "Telefonica Germany GmbH & Co. OHG\nKundenbetreuung\n90345 Nuernberg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kuendigung per Brief oder ueber Mein O2 online.",
  },
  {
    id: "1und1",
    name: "1&1",
    category: "telekommunikation",
    address: "1&1 Telecom GmbH\nElgendorfer Strasse 57\n56410 Montabaur",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung am besten per Einschreiben senden.",
  },
  {
    id: "freenet",
    name: "freenet",
    category: "telekommunikation",
    address: "freenet AG\nHollerstrasse 126\n24782 Buedelsdorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Verschiedene Marken (mobilcom-debitel, klarmobil). Vertrag pruefen!",
  },
  {
    id: "mobilcom-debitel",
    name: "mobilcom-debitel",
    category: "telekommunikation",
    address: "freenet AG\nHollerstrasse 126\n24782 Buedelsdorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehoert zur freenet-Gruppe. Kuendigung auch online im Kundencenter.",
  },

  // ========== MOBILFUNK ==========
  {
    id: "congstar",
    name: "congstar",
    category: "mobilfunk",
    address: "congstar GmbH\nKundenservice\n50969 Koeln",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate (Allnet Flat), keine (Prepaid)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Prepaid-Tarife sind jederzeit kuendbar.",
  },
  {
    id: "aldi-talk",
    name: "ALDI TALK",
    category: "mobilfunk",
    address: "Medion AG\nAm Zehnthof 77\n45307 Essen",
    kuendigungsfrist: "Keine (Prepaid)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Prepaid-Karte jederzeit kuendbar. E-Mail: kundenservice@alditalk.de",
  },
  {
    id: "lidl-connect",
    name: "Lidl Connect",
    category: "mobilfunk",
    address: "Lidl Connect Kundenbetreuung\nPostfach 10 01 53\n40001 Duesseldorf",
    kuendigungsfrist: "Keine (Prepaid)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Prepaid-Karte. Kuendigung jederzeit moeglich.",
  },
  {
    id: "klarmobil",
    name: "klarmobil",
    category: "mobilfunk",
    address: "klarmobil GmbH\nHollerstrasse 126\n24782 Buedelsdorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate (Laufzeitvertrag)",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Gehoert zur freenet-Gruppe.",
  },
  {
    id: "blau",
    name: "Blau",
    category: "mobilfunk",
    address: "Blau Service GmbH\n90345 Nuernberg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate / monatlich kuendbar",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehoert zum O2/Telefonica-Netz.",
  },
  {
    id: "simyo",
    name: "simyo",
    category: "mobilfunk",
    address: "Telefonica Germany GmbH & Co. OHG\n90345 Nuernberg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Marke von Telefonica/O2.",
  },
  {
    id: "otelo",
    name: "otelo",
    category: "mobilfunk",
    address: "Vodafone GmbH\n40549 Duesseldorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Discount-Marke von Vodafone.",
  },
  {
    id: "winSIM",
    name: "winSIM",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Roentgen-Strasse 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate / monatlich kuendbar",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Gehoert zur Drillisch/1&1-Gruppe.",
  },
  {
    id: "premiumsim",
    name: "PremiumSIM",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Roentgen-Strasse 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate / monatlich kuendbar",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Drillisch-Marke. Monatlich kuendbare Tarife verfuegbar.",
  },
  {
    id: "fraenk",
    name: "fraenk",
    category: "mobilfunk",
    address: "fraenk (Telekom)\n53171 Bonn",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Monatlich kuendbar ueber die fraenk-App.",
  },

  // ========== VERSICHERUNG ==========
  {
    id: "allianz",
    name: "Allianz Versicherung",
    category: "versicherung",
    address: "Allianz Versicherungs-AG\n10900 Berlin",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkuendigungsrecht bei Beitragserhohung. Vertragsnummer angeben!",
  },
  {
    id: "huk-coburg",
    name: "HUK-COBURG",
    category: "versicherung",
    address: "HUK-COBURG\nBahnhofsplatz\n96450 Coburg",
    kuendigungsfrist: "1 Monat zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kfz-Versicherung: Stichtag ist der 30. November.",
  },
  {
    id: "ergo",
    name: "ERGO Versicherung",
    category: "versicherung",
    address: "ERGO Versicherung AG\n40198 Duesseldorf",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer und Versicherungsscheinnummer im Schreiben angeben.",
  },
  {
    id: "axa",
    name: "AXA Versicherung",
    category: "versicherung",
    address: "AXA Konzern AG\n51171 Koeln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkuendigungsrecht bei Beitragsanpassung innerhalb eines Monats.",
  },
  {
    id: "debeka",
    name: "Debeka",
    category: "versicherung",
    address: "Debeka\nFerdinand-Sauerbruch-Strasse 18\n56073 Koblenz",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Krankenversicherung: Besondere Regelungen beachten!",
  },
  {
    id: "generali",
    name: "Generali Versicherung",
    category: "versicherung",
    address: "Generali Deutschland AG\nAdenauerring 7\n81737 Muenchen",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkuendigungsrecht bei Beitragserhohung.",
  },
  {
    id: "zurich",
    name: "Zurich Versicherung",
    category: "versicherung",
    address: "Zurich Gruppe Deutschland\nSolmsstrasse 27-37\n60486 Frankfurt am Main",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer unbedingt angeben.",
  },
  {
    id: "dkv",
    name: "DKV (Deutsche Krankenversicherung)",
    category: "versicherung",
    address: "DKV AG\n50594 Koeln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "PKV-Kuendigung: Nachweis der Anschlussversicherung erforderlich!",
  },
  {
    id: "lvm",
    name: "LVM Versicherung",
    category: "versicherung",
    address: "LVM Versicherung\nKolde-Ring 21\n48151 Muenster",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung ueber den Vertreter oder per Einschreiben.",
  },
  {
    id: "devk",
    name: "DEVK Versicherung",
    category: "versicherung",
    address: "DEVK Versicherungen\nRiehler Strasse 190\n50735 Koeln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkuendigungsrecht nach Schadensfall.",
  },
  {
    id: "wuerttembergische",
    name: "Wuerttembergische Versicherung",
    category: "versicherung",
    address: "Wuerttembergische Versicherung AG\n70163 Stuttgart",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer und Sparte angeben.",
  },
  {
    id: "gothaer",
    name: "Gothaer Versicherung",
    category: "versicherung",
    address: "Gothaer Allgemeine Versicherung AG\n50598 Koeln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Per Einschreiben senden.",
  },
  {
    id: "signal-iduna",
    name: "SIGNAL IDUNA",
    category: "versicherung",
    address: "SIGNAL IDUNA Gruppe\nJoseph-Scherer-Strasse 3\n44139 Dortmund",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer angeben.",
  },
  {
    id: "hdi",
    name: "HDI Versicherung",
    category: "versicherung",
    address: "HDI Versicherung AG\n30659 Hannover",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Einschreiben empfohlen.",
  },
  {
    id: "nuernberger",
    name: "Nuernberger Versicherung",
    category: "versicherung",
    address: "Nuernberger Versicherung AG\n90334 Nuernberg",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertrag und Versicherungsscheinnummer angeben.",
  },
  {
    id: "r-und-v",
    name: "R+V Versicherung",
    category: "versicherung",
    address: "R+V Allgemeine Versicherung AG\n65181 Wiesbaden",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Genossenschaftliche Versicherung. Berater kontaktieren empfohlen.",
  },
  {
    id: "barmer",
    name: "BARMER (Krankenkasse)",
    category: "versicherung",
    address: "BARMER\n42271 Wuppertal",
    kuendigungsfrist: "2 Monate zum Monatsende (nach 12 Monaten Bindung)",
    mindestlaufzeit: "18 Monate bei Neuwahl",
    kuendigungsart: ["Schriftlich"],
    hinweise: "GKV-Wechsel: Neue Kasse vor Kuendigung waehlen! Sonderkuendigung bei Zusatzbeitragserhoehung.",
  },
  {
    id: "tk",
    name: "Techniker Krankenkasse (TK)",
    category: "versicherung",
    address: "Techniker Krankenkasse\n22291 Hamburg",
    kuendigungsfrist: "2 Monate zum Monatsende",
    mindestlaufzeit: "18 Monate bei Neuwahl",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Mitgliedschaft bei der neuen Kasse nachweisen!",
  },
  {
    id: "aok",
    name: "AOK",
    category: "versicherung",
    address: "(Adresse Ihrer regionalen AOK eintragen)",
    kuendigungsfrist: "2 Monate zum Monatsende",
    mindestlaufzeit: "18 Monate bei Neuwahl",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Regionale AOK-Adressen variieren. GKV-Wechsel: Nachweis der neuen Kasse beilegen.",
  },
  {
    id: "dak",
    name: "DAK-Gesundheit",
    category: "versicherung",
    address: "DAK-Gesundheit\n22097 Hamburg",
    kuendigungsfrist: "2 Monate zum Monatsende",
    mindestlaufzeit: "18 Monate bei Neuwahl",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkuendigungsrecht bei Zusatzbeitragserhoehung.",
  },

  // ========== ENERGIE ==========
  {
    id: "eon",
    name: "E.ON Energie",
    category: "energie",
    address: "E.ON Energie Deutschland GmbH\n80335 Muenchen",
    kuendigungsfrist: "1 Monat (Grundversorgung) / vertragsabhaengig",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "In der Grundversorgung: 2 Wochen Kuendigungsfrist.",
  },
  {
    id: "vattenfall",
    name: "Vattenfall",
    category: "energie",
    address: "Vattenfall Europe Sales GmbH\n10115 Berlin",
    kuendigungsfrist: "1 Monat (Grundversorgung) / vertragsabhaengig",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorgung: 2 Wochen Frist. Bei Umzug Sonderkuendigungsrecht.",
  },
  {
    id: "rwe",
    name: "RWE / innogy",
    category: "energie",
    address: "RWE AG\nHuyssenallee 2\n45128 Essen",
    kuendigungsfrist: "Vertragsabhaengig",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsbedingungen im Einzelfall pruefen.",
  },
  {
    id: "enbw",
    name: "EnBW",
    category: "energie",
    address: "EnBW Energie Baden-Wuerttemberg AG\n76131 Karlsruhe",
    kuendigungsfrist: "1 Monat (Grundversorgung)",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorgung jederzeit mit 2 Wochen Frist kuendbar.",
  },
  {
    id: "stadtwerke-muenchen",
    name: "Stadtwerke Muenchen (SWM)",
    category: "energie",
    address: "Stadtwerke Muenchen GmbH\n80287 Muenchen",
    kuendigungsfrist: "1 Monat (Grundversorgung)",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorgung: 2 Wochen Frist.",
  },
  {
    id: "yello",
    name: "Yello Strom",
    category: "energie",
    address: "Yello Strom GmbH\n50823 Koeln",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Tochter der EnBW.",
  },
  {
    id: "eprimo",
    name: "eprimo",
    category: "energie",
    address: "eprimo GmbH\n63263 Neu-Isenburg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Tochterunternehmen von E.ON. Online-Kuendigung moeglich.",
  },
  {
    id: "lichtblick",
    name: "LichtBlick",
    category: "energie",
    address: "LichtBlick SE\nZirkusweg 6\n20359 Hamburg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "Keine (monatlich kuendbar)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Oekostrom-Anbieter. Monatlich kuendbar.",
  },
  {
    id: "naturstrom",
    name: "NATURSTROM",
    category: "energie",
    address: "NATURSTROM AG\n40237 Duesseldorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "Keine (monatlich kuendbar)",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Oekostrom-Anbieter.",
  },
  {
    id: "envia-m",
    name: "enviaM",
    category: "energie",
    address: "envia Mitteldeutsche Energie AG\n09111 Chemnitz",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regionalversorger fuer Mitteldeutschland.",
  },

  // ========== FITNESS ==========
  {
    id: "mcfit",
    name: "McFIT",
    category: "fitness",
    address: "RSG Group GmbH\nFranz-Ehrlich-Strasse 5\n12489 Berlin",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online-Kuendigung ueber Mitgliederbereich. Einschreiben empfohlen.",
  },
  {
    id: "fitx",
    name: "FitX",
    category: "fitness",
    address: "FitX Deutschland GmbH\nUeberseering 33b\n22297 Hamburg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung per Einschreiben an die Studioadresse senden.",
  },
  {
    id: "fitness-first",
    name: "Fitness First",
    category: "fitness",
    address: "Fitness First Germany GmbH\n60329 Frankfurt am Main",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung muss vor Ort oder schriftlich erfolgen.",
  },
  {
    id: "clever-fit",
    name: "clever fit",
    category: "fitness",
    address: "clever fit GmbH\n86199 Augsburg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung an das jeweilige Studio senden.",
  },
  {
    id: "urban-sports",
    name: "Urban Sports Club",
    category: "fitness",
    address: "Urban Sports Club\nKoepenicker Str. 9\n10997 Berlin",
    kuendigungsfrist: "1 Monat",
    mindestlaufzeit: "Keine (monatlich kuendbar)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber die App oder das Online-Konto.",
  },
  {
    id: "john-reed",
    name: "John Reed Fitness",
    category: "fitness",
    address: "RSG Group GmbH\nFranz-Ehrlich-Strasse 5\n12489 Berlin",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Gehoert zur RSG Group (wie McFIT). Einschreiben empfohlen.",
  },
  {
    id: "bodystreet",
    name: "Bodystreet (EMS-Training)",
    category: "fitness",
    address: "(Adresse Ihres lokalen Bodystreet Studios eintragen)",
    kuendigungsfrist: "Vertragsabhaengig (meist 3 Monate)",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "EMS-Studio. Kuendigung direkt an das Franchise-Studio senden.",
  },
  {
    id: "kieser-training",
    name: "Kieser Training",
    category: "fitness",
    address: "(Adresse Ihres lokalen Kieser Studios eintragen)",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung an die jeweilige Studioadresse.",
  },

  // ========== STREAMING ==========
  {
    id: "netflix",
    name: "Netflix",
    category: "streaming",
    address: "Netflix International B.V.\nKarperstraat 8-10\n1075 KZ Amsterdam, Niederlande",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung direkt ueber die Netflix-Kontoeinstellungen.",
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "streaming",
    address: "Spotify AB\nRegeringsgatan 19\n111 53 Stockholm, Schweden",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber spotify.com/account.",
  },
  {
    id: "amazon-prime",
    name: "Amazon Prime",
    category: "streaming",
    address: "Amazon Europe Core S.a r.l.\n38 avenue John F. Kennedy\nL-1855 Luxemburg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Amazon-Kontoeinstellungen. Anteilige Erstattung moeglich.",
  },
  {
    id: "dazn",
    name: "DAZN",
    category: "streaming",
    address: "DAZN Limited\n12 Hammersmith Grove\nLondon W6 7AP, UK",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Abhaengig vom gewaehlten Abo",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber die DAZN-App oder Webseite.",
  },
  {
    id: "sky",
    name: "Sky Deutschland",
    category: "streaming",
    address: "Sky Deutschland Fernsehen GmbH & Co. KG\nMedienallee 26\n85774 Unterfoehring",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online", "Telefon"],
    hinweise: "Telefon: 089 99 72 79 00. Per Brief oder Fax.",
  },
  {
    id: "disney-plus",
    name: "Disney+",
    category: "streaming",
    address: "The Walt Disney Company (Benelux) B.V.\nDe Passage 144\n1101 AX Amsterdam, Niederlande",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber die Disney+ Kontoeinstellungen.",
  },
  {
    id: "apple-tv-plus",
    name: "Apple TV+",
    category: "streaming",
    address: "Apple Distribution International Ltd.\nHollyhill Industrial Estate\nCork, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Apple-ID Einstellungen.",
  },
  {
    id: "wow-sky",
    name: "WOW (ehem. Sky Ticket)",
    category: "streaming",
    address: "Sky Deutschland Fernsehen GmbH & Co. KG\n85774 Unterfoehring",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber wow.sky.de.",
  },
  {
    id: "rtlplus",
    name: "RTL+",
    category: "streaming",
    address: "RTL interactive GmbH\nPicassoplatz 1\n50679 Koeln",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber rtlplus.de Kontoeinstellungen.",
  },
  {
    id: "joyn",
    name: "Joyn PLUS+",
    category: "streaming",
    address: "Joyn GmbH\n80335 Muenchen",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber das Joyn-Konto.",
  },
  {
    id: "audible",
    name: "Audible",
    category: "streaming",
    address: "Audible GmbH\nLehrter Strasse 57\n10557 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber audible.de Kontoeinstellungen. Guthaben bleibt erhalten.",
  },
  {
    id: "deezer",
    name: "Deezer",
    category: "streaming",
    address: "Deezer SA\n24 rue de Calais\n75009 Paris, Frankreich",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber deezer.com Kontoeinstellungen.",
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    category: "streaming",
    address: "Google Ireland Ltd.\nGordon House\nBarrow Street, Dublin 4, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Google-Kontoeinstellungen.",
  },

  // ========== BANK & FINANZEN ==========
  {
    id: "sparkasse",
    name: "Sparkasse",
    category: "bank",
    address: "(Adresse Ihrer lokalen Sparkasse eintragen)",
    kuendigungsfrist: "Jederzeit (Girokonto)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Girokonto jederzeit kuendbar. Alle Dauerauftraege vorher aendern!",
  },
  {
    id: "dkb",
    name: "DKB (Deutsche Kreditbank)",
    category: "bank",
    address: "Deutsche Kreditbank AG\nTaubenstrasse 7-9\n10117 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Konto vorher auf 0 bringen. Neue Bankverbindung fuer Dauerauftraege einrichten.",
  },
  {
    id: "ing",
    name: "ING",
    category: "bank",
    address: "ING-DiBa AG\n60628 Frankfurt am Main",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kuendigung ueber das Internetbanking moeglich.",
  },
  {
    id: "commerzbank",
    name: "Commerzbank",
    category: "bank",
    address: "Commerzbank AG\n60261 Frankfurt am Main",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigungsschreiben per Einschreiben senden.",
  },
  {
    id: "n26",
    name: "N26",
    category: "bank",
    address: "N26 Bank GmbH\nVoltairestrasse 8\n10179 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Kuendigung direkt ueber die N26-App. E-Mail: support@n26.com",
  },
  {
    id: "deutsche-bank",
    name: "Deutsche Bank",
    category: "bank",
    address: "Deutsche Bank AG\n60262 Frankfurt am Main",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung schriftlich an die kontofuehrende Filiale.",
  },
  {
    id: "postbank",
    name: "Postbank",
    category: "bank",
    address: "Deutsche Bank AG (Postbank)\n53113 Bonn",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Seit 2023 Teil der Deutschen Bank.",
  },
  {
    id: "comdirect",
    name: "comdirect",
    category: "bank",
    address: "comdirect (Commerzbank AG)\n25449 Quickborn",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehoert zur Commerzbank. Online-Kuendigung moeglich.",
  },
  {
    id: "targobank",
    name: "TARGOBANK",
    category: "bank",
    address: "TARGOBANK AG\n40210 Duesseldorf",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Girokonto jederzeit kuendbar. Kreditvertraege haben separate Fristen.",
  },
  {
    id: "volksbank",
    name: "Volksbank / Raiffeisenbank",
    category: "bank",
    address: "(Adresse Ihrer lokalen Volksbank eintragen)",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Genossenschaftsbank. Kuendigung an die lokale Filiale.",
  },
  {
    id: "consorsbank",
    name: "Consorsbank",
    category: "bank",
    address: "BNP Paribas S.A. Niederlassung Deutschland\n90318 Nuernberg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online- oder schriftliche Kuendigung.",
  },
  {
    id: "santander",
    name: "Santander Consumer Bank",
    category: "bank",
    address: "Santander Consumer Bank AG\n41061 Moenchengladbach",
    kuendigungsfrist: "Jederzeit (Konto) / Vertragsabhaengig (Kredit)",
    mindestlaufzeit: "Keine (Konto)",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kreditvertraege: Sondertilgungsrecht pruefen.",
  },
  {
    id: "scalable-capital",
    name: "Scalable Capital",
    category: "bank",
    address: "Scalable Capital GmbH\nSeitzstrasse 8e\n80538 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Depot-Kuendigung ueber die App. Alle Wertpapiere vorher uebertragen oder verkaufen.",
  },
  {
    id: "trade-republic",
    name: "Trade Republic",
    category: "bank",
    address: "Trade Republic Bank GmbH\nKastanienallee 32\n10435 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Depot-Kuendigung ueber die App. Guthaben vorher ueberweisen.",
  },

  // ========== INTERNET & DSL ==========
  {
    id: "unitymedia",
    name: "Unitymedia / Vodafone Kabel",
    category: "internet",
    address: "Vodafone GmbH\nKundenbetreuung\n40549 Duesseldorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Nach Uebernahme durch Vodafone: Kuendigung an Vodafone richten.",
  },
  {
    id: "pyur",
    name: "PYUR / Tele Columbus",
    category: "internet",
    address: "Tele Columbus AG\n10587 Berlin",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung per Einschreiben empfohlen.",
  },
  {
    id: "easybell",
    name: "easybell",
    category: "internet",
    address: "easybell GmbH\nErkelenzdamm 61-63\n10999 Berlin",
    kuendigungsfrist: "1 Monat",
    mindestlaufzeit: "Keine (monatlich kuendbar)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Monatlich kuendbar. Kuendigung ueber das Kundenportal.",
  },
  {
    id: "m-net",
    name: "M-net",
    category: "internet",
    address: "M-net Telekommunikations GmbH\n80339 Muenchen",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Regionalanbieter in Bayern.",
  },
  {
    id: "netcologne",
    name: "NetCologne",
    category: "internet",
    address: "NetCologne GmbH\n50667 Koeln",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Regionalanbieter im Raum Koeln.",
  },
  {
    id: "waipu-tv",
    name: "waipu.tv",
    category: "internet",
    address: "EXARING AG\nMuenzstrasse 18\n10178 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber waipu.tv Kontoeinstellungen.",
  },

  // ========== VERLAG & ZEITSCHRIFTEN ==========
  {
    id: "spiegel",
    name: "Der Spiegel",
    category: "verlag",
    address: "DER SPIEGEL GmbH & Co. KG\nAbo-Service\n20637 Hamburg",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "E-Mail: abo@spiegel.de. Kundennummer angeben.",
  },
  {
    id: "zeit",
    name: "Die Zeit",
    category: "verlag",
    address: "Zeitverlag Gerd Bucerius GmbH & Co. KG\nAbo-Service\n20080 Hamburg",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "E-Mail: abo@zeit.de",
  },
  {
    id: "sueddeutsche",
    name: "Sueddeutsche Zeitung",
    category: "verlag",
    address: "Sueddeutsche Zeitung GmbH\nAbo-Service\n80289 Muenchen",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung per Brief oder Fax an den Abo-Service.",
  },
  {
    id: "bild",
    name: "BILD / BILDplus",
    category: "verlag",
    address: "Axel Springer SE\nAbo-Service\n20350 Hamburg",
    kuendigungsfrist: "Jederzeit zum Monatsende (Digital)",
    mindestlaufzeit: "Keine (Digital-Abo)",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Digital-Abo online kuendbar. Print-Abo: Fristen pruefen.",
  },
  {
    id: "faz",
    name: "Frankfurter Allgemeine Zeitung (FAZ)",
    category: "verlag",
    address: "Frankfurter Allgemeine Zeitung GmbH\nAbo-Service\n60267 Frankfurt am Main",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "E-Mail: abo-service@faz.de",
  },
  {
    id: "welt",
    name: "Die Welt / WELTplus",
    category: "verlag",
    address: "Axel Springer SE\nAbo-Service\n10888 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende (Digital)",
    mindestlaufzeit: "Keine (Digital-Abo)",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Digital-Abo ueber Kontoeinstellungen kuendbar.",
  },
  {
    id: "focus",
    name: "FOCUS",
    category: "verlag",
    address: "BurdaVerlag GmbH\nAbo-Service\n77649 Offenburg",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kundennummer im Schreiben angeben.",
  },
  {
    id: "stern",
    name: "stern",
    category: "verlag",
    address: "Gruner + Jahr GmbH\nAbo-Service\n20637 Hamburg",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Gehoert zur RTL-Gruppe.",
  },
  {
    id: "handelsblatt",
    name: "Handelsblatt",
    category: "verlag",
    address: "Handelsblatt GmbH\nAbo-Service\n40210 Duesseldorf",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "E-Mail: leserservice@handelsblatt.com",
  },

  // ========== MITGLIEDSCHAFT & VEREIN ==========
  {
    id: "adac",
    name: "ADAC",
    category: "mitgliedschaft",
    address: "ADAC e.V.\n81360 Muenchen",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Mitgliedschaft verlaengert sich automatisch. Einschreiben empfohlen.",
  },
  {
    id: "gewerkschaft-verdi",
    name: "ver.di Gewerkschaft",
    category: "mitgliedschaft",
    address: "ver.di\nPaula-Thiede-Ufer 10\n10179 Berlin",
    kuendigungsfrist: "3 Monate zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Austritt zum Ende eines Kalendervierteljahres.",
  },
  {
    id: "bahncard",
    name: "BahnCard (Deutsche Bahn)",
    category: "mitgliedschaft",
    address: "Deutsche Bahn AG\nBahnCard-Service\n60643 Frankfurt am Main",
    kuendigungsfrist: "6 Wochen vor Ablauf",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online", "Telefon"],
    hinweise: "Online-Kuendigung ueber bahn.de. Telefon: 030 2970.",
  },
  {
    id: "ig-metall",
    name: "IG Metall",
    category: "mitgliedschaft",
    address: "IG Metall Vorstand\nWilhelm-Leuschner-Strasse 79\n60329 Frankfurt am Main",
    kuendigungsfrist: "3 Monate zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Austritt schriftlich an die Verwaltungsstelle.",
  },
  {
    id: "gez-rundfunkbeitrag",
    name: "Rundfunkbeitrag (GEZ)",
    category: "mitgliedschaft",
    address: "ARD ZDF Deutschlandradio Beitragsservice\n50656 Koeln",
    kuendigungsfrist: "Abmeldung bei Abmeldung/Umzug",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Abmeldung nur bei Abmeldung der Wohnung, Umzug ins Ausland o.ae. Befreiung beantragen bei geringem Einkommen.",
  },
  {
    id: "amazon-prime-member",
    name: "Amazon Prime (Mitgliedschaft)",
    category: "mitgliedschaft",
    address: "Amazon Europe Core S.a r.l.\n38 avenue John F. Kennedy\nL-1855 Luxemburg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Amazon-Konto. Anteilige Erstattung bei Jahresabo moeglich.",
  },
  {
    id: "automobilclub-ace",
    name: "ACE Auto Club Europa",
    category: "mitgliedschaft",
    address: "ACE Auto Club Europa e.V.\n70372 Stuttgart",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Alternative zum ADAC.",
  },
  {
    id: "avc",
    name: "AvD (Automobilclub von Deutschland)",
    category: "mitgliedschaft",
    address: "Automobilclub von Deutschland e.V.\n60487 Frankfurt am Main",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Einschreiben empfohlen.",
  },

  // ========== SONSTIGES ==========
  {
    id: "check24",
    name: "CHECK24",
    category: "sonstiges",
    address: "CHECK24 Vergleichsportal GmbH\nErika-Mann-Str. 62-66\n80636 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto jederzeit loeschbar. E-Mail: kundenservice@check24.de",
  },
  {
    id: "parship",
    name: "Parship",
    category: "sonstiges",
    address: "PE Digital GmbH\nSpeersort 10\n20095 Hamburg",
    kuendigungsfrist: "12 Wochen zum Vertragsende",
    mindestlaufzeit: "6 Monate",
    kuendigungsart: ["Schriftlich", "Fax"],
    hinweise: "Widerruf innerhalb von 14 Tagen. Danach: 12 Wochen Frist.",
  },
  {
    id: "elitepartner",
    name: "ElitePartner",
    category: "sonstiges",
    address: "PE Digital GmbH\nSpeersort 10\n20095 Hamburg",
    kuendigungsfrist: "12 Wochen zum Vertragsende",
    mindestlaufzeit: "6 Monate",
    kuendigungsart: ["Schriftlich", "Fax"],
    hinweise: "Gleiche Frist wie Parship. Widerruf 14 Tage moeglich.",
  },
  {
    id: "verivox",
    name: "Verivox",
    category: "sonstiges",
    address: "Verivox GmbH\n69115 Heidelberg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Vergleichsportal. Konto jederzeit loeschbar.",
  },
  {
    id: "schufa",
    name: "SCHUFA (meineSCHUFA)",
    category: "sonstiges",
    address: "SCHUFA Holding AG\nKormoranweg 5\n65201 Wiesbaden",
    kuendigungsfrist: "Abhaengig vom Paket",
    mindestlaufzeit: "Abhaengig vom Paket",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "meineSCHUFA-Paket online kuendbar.",
  },
  {
    id: "payback",
    name: "PAYBACK",
    category: "sonstiges",
    address: "PAYBACK GmbH\nTheresienhöhe 12\n80339 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Punkte vor Kuendigung einloesen! E-Mail: service@payback.de",
  },
  {
    id: "deutschlandcard",
    name: "DeutschlandCard",
    category: "sonstiges",
    address: "DeutschlandCard GmbH\n81671 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Punkte vor Kuendigung einloesen.",
  },
  {
    id: "immoscout24",
    name: "ImmobilienScout24",
    category: "sonstiges",
    address: "Immobilien Scout GmbH\nAndreasstrasse 10\n10243 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende (Premium)",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "MieterPlus/ImmobilienScout24 Premium kuendbar ueber das Konto.",
  },
  {
    id: "ebay-kleinanzeigen",
    name: "Kleinanzeigen (ehem. eBay)",
    category: "sonstiges",
    address: "Kleinanzeigen GmbH\n10969 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kostenloses Konto. Bezahlte Dienste online kuendbar.",
  },
  {
    id: "lieferando",
    name: "Lieferando",
    category: "sonstiges",
    address: "Takeaway.com Group B.V.\nOosterdoksstraat 80\n1011 DK Amsterdam, Niederlande",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto loeschbar ueber Kontoeinstellungen.",
  },
  {
    id: "hellofresh",
    name: "HelloFresh",
    category: "sonstiges",
    address: "HelloFresh SE\nSaarbruecker Strasse 37a\n10405 Berlin",
    kuendigungsfrist: "Jederzeit (vor Bestellfrist der naechsten Woche)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Abo pausieren oder kuendigen ueber die App/Webseite.",
  },
  {
    id: "marley-spoon",
    name: "Marley Spoon",
    category: "sonstiges",
    address: "Marley Spoon GmbH\n10999 Berlin",
    kuendigungsfrist: "Jederzeit (vor Bestellfrist)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kochbox-Abo jederzeit pausierbar/kuendbar.",
  },
  {
    id: "mydays",
    name: "mydays",
    category: "sonstiges",
    address: "mydays GmbH\n81541 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["E-Mail"],
    hinweise: "Konto loeschbar per E-Mail an den Kundenservice.",
  },
  {
    id: "tinder",
    name: "Tinder",
    category: "sonstiges",
    address: "Match Group, LLC\n8750 N. Central Expressway\nDallas, TX 75231, USA",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber App Store / Google Play oder tinder.com.",
  },
  {
    id: "bumble",
    name: "Bumble",
    category: "sonstiges",
    address: "Bumble Inc.\nAustin, TX, USA",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber App Store / Google Play.",
  },
  {
    id: "mcdonalds-app",
    name: "McDonald's App (MyMcDonald's Rewards)",
    category: "sonstiges",
    address: "McDonald's Deutschland LLC\n80339 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Konto loeschbar ueber App-Einstellungen.",
  },
  {
    id: "flixbus",
    name: "FlixBus / Flixtrain",
    category: "sonstiges",
    address: "FlixMobility GmbH\nFriedenheimerbruecke 16\n80639 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto loeschbar. Einzelbuchungen stornierbar je nach Tarif.",
  },
  {
    id: "sixt",
    name: "SIXT (Abo/Flatrate)",
    category: "sonstiges",
    address: "Sixt SE\nZugspitzstrasse 1\n82049 Pullach",
    kuendigungsfrist: "Vertragsabhaengig",
    mindestlaufzeit: "Abhaengig vom Abo-Modell",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Auto-Abo Kuendigungsfristen im Vertrag pruefen.",
  },
  {
    id: "miles",
    name: "MILES Carsharing",
    category: "sonstiges",
    address: "MILES Mobility GmbH\n10997 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto loeschbar ueber die App.",
  },
  {
    id: "share-now",
    name: "SHARE NOW",
    category: "sonstiges",
    address: "SHARE NOW GmbH\n10117 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Konto kuendbar ueber die App.",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    category: "sonstiges",
    address: "Dropbox International Unlimited Company\nDublin, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber dropbox.com Kontoeinstellungen.",
  },
  {
    id: "icloud",
    name: "iCloud+ (Apple)",
    category: "sonstiges",
    address: "Apple Distribution International Ltd.\nCork, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Apple-ID Einstellungen.",
  },
  {
    id: "microsoft365",
    name: "Microsoft 365",
    category: "sonstiges",
    address: "Microsoft Ireland Operations Ltd.\nDublin, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber account.microsoft.com.",
  },
  {
    id: "google-one",
    name: "Google One",
    category: "sonstiges",
    address: "Google Ireland Ltd.\nDublin 4, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Google-Kontoeinstellungen.",
  },
  {
    id: "adobe-cc",
    name: "Adobe Creative Cloud",
    category: "sonstiges",
    address: "Adobe Systems Software Ireland Ltd.\nDublin, Irland",
    kuendigungsfrist: "14 Tage Widerruf / Vorzeitige Kuendigung mit Gebuehr",
    mindestlaufzeit: "12 Monate (Jahresabo)",
    kuendigungsart: ["Online"],
    hinweise: "Vorzeitige Kuendigung des Jahresabos: 50% der Restlaufzeit als Gebuehr.",
  },
  {
    id: "linkedin-premium",
    name: "LinkedIn Premium",
    category: "sonstiges",
    address: "LinkedIn Ireland Unlimited Company\nDublin, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber linkedin.com Kontoeinstellungen.",
  },
  {
    id: "xing-premium",
    name: "XING Premium",
    category: "sonstiges",
    address: "New Work SE\nDammtorstrasse 30\n20354 Hamburg",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo) / 12 Monate (Jahresabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber xing.com Kontoeinstellungen.",
  },
  {
    id: "chatgpt-plus",
    name: "ChatGPT Plus (OpenAI)",
    category: "sonstiges",
    address: "OpenAI LLC\nSan Francisco, CA, USA",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber chat.openai.com Kontoeinstellungen.",
  },
  // ========== NEUE ERGÄNZUNGEN ==========
  {
    id: "wuestenrot",
    name: "Wüstenrot Bausparkasse",
    category: "bank",
    address: "Wüstenrot Bausparkasse AG\nWüstenrotstr. 1\n71630 Ludwigsburg",
    kuendigungsfrist: "3 Monate zum Quartalsende",
    mindestlaufzeit: "Laufzeit laut Bausparvertrag",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Bausparvertrag kann nach Zuteilungsreife jederzeit gekündigt werden.",
  },
  {
    id: "cosmos-direkt",
    name: "CosmosDirekt",
    category: "versicherung",
    address: "CosmosDirekt\nHalbergstraße 50-60\n66121 Saarbrücken",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Sonderkündigungsrecht bei Beitragserhöhung innerhalb eines Monats.",
  },
  {
    id: "provinzial",
    name: "Provinzial Versicherung",
    category: "versicherung",
    address: "Provinzial Holding AG\nProvinzialplatz 1\n40215 Düsseldorf",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Regionale Unterschiede bei Ansprechpartnern möglich (Rheinland/Nordwest).",
  },
  {
    id: "swb-energie",
    name: "swb Energie",
    category: "energie",
    address: "swb AG\nTheodor-Heuss-Allee 20\n28215 Bremen",
    kuendigungsfrist: "6 Wochen zum Vertragsende (Sondertarife)",
    mindestlaufzeit: "Je nach Tarif",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorgung: 2 Wochen Kündigungsfrist.",
  },
  {
    id: "mainova",
    name: "Mainova",
    category: "energie",
    address: "Mainova AG\nSolmsstraße 38\n60486 Frankfurt am Main",
    kuendigungsfrist: "6 Wochen zum Vertragsende",
    mindestlaufzeit: "12 Monate (Sondertarife)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorgung kann mit 2 Wochen Frist gekündigt werden.",
  },
  {
    id: "entega",
    name: "ENTEGA",
    category: "energie",
    address: "ENTEGA Plus GmbH\nFrankfurter Str. 110\n64293 Darmstadt",
    kuendigungsfrist: "6 Wochen zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Ökostrom- und Ökogas-Anbieter aus Südhessen.",
  },
  {
    id: "mrs-sporty",
    name: "Mrs.Sporty",
    category: "fitness",
    address: "Mrs.Sporty GmbH\nNiederlassung vor Ort\n(Adresse je nach Studio)",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kündigung an das jeweilige Studio richten.",
  },
  {
    id: "injoy",
    name: "INJOY Fitness",
    category: "fitness",
    address: "INJOY Fitness (lokales Studio)\n(Adresse je nach Standort)",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "12–24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Franchise-Unternehmen – Kündigung direkt an das Studio.",
  },
  {
    id: "paramount-plus",
    name: "Paramount+",
    category: "streaming",
    address: "Paramount Global\nDublin, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über Kontoeinstellungen auf paramountplus.com.",
  },
  {
    id: "crunchyroll",
    name: "Crunchyroll",
    category: "streaming",
    address: "Crunchyroll LLC\nSan Francisco, CA, USA",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo) / 12 Monate (Jahresabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über crunchyroll.com Kontoeinstellungen.",
  },
  {
    id: "berliner-zeitung",
    name: "Berliner Zeitung",
    category: "verlag",
    address: "Berliner Verlag GmbH\nAlte Jakobstraße 105\n10969 Berlin",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Je nach Abo-Modell",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Digital-Abo kann online gekündigt werden.",
  },
  {
    id: "rheinische-post",
    name: "Rheinische Post",
    category: "verlag",
    address: "Rheinische Post Mediengruppe\nZülpicher Str. 10\n40196 Düsseldorf",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Je nach Abo-Modell",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Kündigungsbestätigung anfordern.",
  },
  {
    id: "vgn-medien",
    name: "Stuttgarter Zeitung",
    category: "verlag",
    address: "Stuttgarter Zeitung Verlagsgesellschaft mbH\nPlieninger Str. 150\n70567 Stuttgart",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Je nach Abo-Modell",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Auch digital-only Abonnements mit gleicher Frist.",
  },
  {
    id: "tier-scooter",
    name: "TIER E-Scooter",
    category: "sonstiges",
    address: "TIER Mobility SE\nAlbertstraße 16\n10827 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Account-Löschung über die App oder per E-Mail an support@tier.app.",
  },
  {
    id: "voi-scooter",
    name: "Voi E-Scooter",
    category: "sonstiges",
    address: "Voi Technology AB\nStockholm, Schweden",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Account-Löschung über die App oder per E-Mail an support@voiapp.io.",
  },
  {
    id: "petolo",
    name: "Petolo Tierkrankenversicherung",
    category: "versicherung",
    address: "dentolo Deutschland GmbH (Petolo)\nTorstraße 33\n10119 Berlin",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Sonderkündigungsrecht bei Beitragserhöhung.",
  },
  {
    id: "clark-versicherung",
    name: "Clark Versicherung",
    category: "versicherung",
    address: "Clark Germany GmbH\nGoethestraße 10\n60313 Frankfurt am Main",
    kuendigungsfrist: "Abhängig vom jeweiligen Vertrag",
    mindestlaufzeit: "Abhängig vom jeweiligen Vertrag",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Clark als Makler kündigt auf Wunsch bei der Versicherung.",
  },
  {
    id: "friendsurance",
    name: "Friendsurance",
    category: "versicherung",
    address: "Friendsurance Deutschland GmbH\nAltenburger Str. 44\n04275 Leipzig",
    kuendigungsfrist: "Abhängig vom jeweiligen Vertrag",
    mindestlaufzeit: "Abhängig vom Versicherungsvertrag",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Kündigung der Friendsurance-Mitgliedschaft und/oder des Versicherungsvertrags separat.",
  },
  
  // ========== ZUSÄTZLICHE TELEKOMMUNIKATION ==========
  {
    id: "pyur2",
    name: "PŸUR",
    category: "internet",
    address: "Tele Columbus AG\nKaiserin-Augusta-Allee 108\n10553 Berlin",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kabel-Internet und TV-Anbieter.",
  },
  {
    id: "ewe",
    name: "EWE Tel",
    category: "telekommunikation",
    address: "EWE TEL GmbH\nCloppenburger Str. 310\n26133 Oldenburg",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regional in Norddeutschland verfügbar.",
  },
  {
    id: "netcologne2",
    name: "NetCologne",
    category: "internet",
    address: "NetCologne Gesellschaft für Telekommunikation mbH\nAm Coloneum 9\n50829 Köln",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online", "Fax"],
    hinweise: "Regionaler Anbieter für Köln und Umgebung.",
  },
  {
    id: "mnet",
    name: "M-net",
    category: "internet",
    address: "M-net Telekommunikations GmbH\nEmmy-Noether-Str. 2\n80992 München",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regional in München und Augsburg.",
  },
  {
    id: "osnatel",
    name: "osnatel",
    category: "telekommunikation",
    address: "EWE TEL GmbH\nDreieichstr. 2\n49074 Osnabrück",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "EWE-Marke für Osnabrück.",
  },
  
  // ========== ZUSÄTZLICHES STREAMING & MEDIEN ==========
  {
    id: "joyn2",
    name: "Joyn PLUS+",
    category: "streaming",
    address: "Joyn GmbH\nPickhuben 2\n20457 Hamburg",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung im Konto unter Einstellungen.",
  },
  {
    id: "rtlplus2",
    name: "RTL+",
    category: "streaming",
    address: "RTL+ Deutschland GmbH\nPickhuben 4\n20457 Hamburg",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Vormals TVNow, jetzt RTL+.",
  },
  {
    id: "waipu",
    name: "waipu.tv",
    category: "streaming",
    address: "EXARING AG\nErnst-Reuter-Platz 10\n10587 Berlin",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine (bei monatlichem Abo)",
    kuendigungsart: ["Online"],
    hinweise: "Live-TV Streaming Service.",
  },
  {
    id: "magentasport",
    name: "MagentaSport",
    category: "streaming",
    address: "Telekom Deutschland GmbH\nLandgrabenweg 151\n53227 Bonn",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Sport-Streaming der Telekom.",
  },
  {
    id: "paramount",
    name: "Paramount+",
    category: "streaming",
    address: "Paramount+ International\nc/o Paramount Germany GmbH\nKemperplatz 1\n10785 Berlin",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über Account-Einstellungen.",
  },
  {
    id: "mubi",
    name: "MUBI",
    category: "streaming",
    address: "MUBI Inc.\n148 Lafayette St\n10013 New York, USA",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Arthouse-Cinema Streaming.",
  },
  {
    id: "crunchyroll2",
    name: "Crunchyroll",
    category: "streaming",
    address: "Crunchyroll LLC\nAttn: Customer Service\nSan Francisco, CA 94102, USA",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Anime-Streaming Service.",
  },
  
  // ========== ZUSÄTZLICHE FITNESS & SPORT ==========
  {
    id: "urbanSportsClub",
    name: "Urban Sports Club",
    category: "fitness",
    address: "Urban Sports GmbH\nPappelallee 78/79\n10437 Berlin",
    kuendigungsfrist: "Monatlich kündbar (bei Flex-Tarifen)",
    mindestlaufzeit: "Keine oder 12 Monate",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Verschiedene Tarife mit unterschiedlichen Laufzeiten.",
  },
  {
    id: "cleverfit",
    name: "clever fit",
    category: "fitness",
    address: "clever fit Franchise GmbH\nKreuzberger Ring 68\n65205 Wiesbaden",
    kuendigungsfrist: "6 Wochen zum Ende der Mindestlaufzeit",
    mindestlaufzeit: "12 oder 24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kündigung beim jeweiligen Studio.",
  },
  {
    id: "hansefitMitarbeiter",
    name: "Hansefit (Firmen)",
    category: "fitness",
    address: "Hansefit GmbH\nDurchschnitt 12\n20146 Hamburg",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Firmenfitness-Programm.",
  },
  {
    id: "mrs-sporty2",
    name: "mrs.sporty",
    category: "fitness",
    address: "mrs.sporty GmbH\nWarthestr. 60\n14513 Teltow",
    kuendigungsfrist: "6 Wochen zum Monatsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Frauenfitness-Studio.",
  },
  {
    id: "kieserTraining",
    name: "Kieser Training",
    category: "fitness",
    address: "Kieser Training AG\nHardturmstrasse 261\n8005 Zürich, Schweiz",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Krafttraining-Studios.",
  },
  {
    id: "crossfit",
    name: "CrossFit Box (Franchise)",
    category: "fitness",
    address: "Individuelle Adresse je nach Box",
    kuendigungsfrist: "Unterschiedlich je nach Box",
    mindestlaufzeit: "Unterschiedlich",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Kündigung direkt bei der jeweiligen Box.",
  },
  
  // ========== ZUSÄTZLICHE VERSICHERUNGEN ==========
  {
    id: "debeka2",
    name: "Debeka",
    category: "versicherung",
    address: "Debeka Versicherungen\nFerdinand-Sauerbruch-Str. 18\n56073 Koblenz",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Private Kranken- und Sachversicherung.",
  },
  {
    id: "devk2",
    name: "DEVK",
    category: "versicherung",
    address: "DEVK Versicherungen\nRiehler Str. 190\n50735 Köln",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regional in NRW stark vertreten.",
  },
  {
    id: "huk24",
    name: "HUK24",
    category: "versicherung",
    address: "HUK24 AG\nHUK-Coburg-Platz\n96450 Coburg",
    kuendigungsfrist: "1 Monat zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Online-Versicherung der HUK-Coburg.",
  },
  {
    id: "vhv",
    name: "VHV Versicherung",
    category: "versicherung",
    address: "VHV Allgemeine Versicherung AG\nVHV-Platz 1\n30177 Hannover",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Spezialisiert auf Autoversicherungen.",
  },
  {
    id: "wgv",
    name: "Württembergische",
    category: "versicherung",
    address: "Württembergische Versicherung AG\nGutenbergstr. 30\n70176 Stuttgart",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Regional in Baden-Württemberg.",
  },
  {
    id: "basler",
    name: "Basler Versicherungen",
    category: "versicherung",
    address: "Basler Versicherungen\nBasler Str. 4\n61352 Bad Homburg",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sachversicherungen.",
  },
  
  // ========== ZUSÄTZLICHE ENERGIE ==========
  {
    id: "mainova2",
    name: "Mainova",
    category: "energie",
    address: "Mainova AG\nSolmsstr. 38\n60486 Frankfurt am Main",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 oder 24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regionalversorger für Frankfurt.",
  },
  {
    id: "swm",
    name: "Stadtwerke München (SWM)",
    category: "energie",
    address: "Stadtwerke München GmbH\nEmmy-Noether-Str. 2\n80992 München",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorger für München.",
  },
  {
    id: "rheinenergie",
    name: "RheinEnergie",
    category: "energie",
    address: "RheinEnergie AG\nParkgürtel 24\n50823 Köln",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine (Grundversorgung)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorger für Köln.",
  },
  {
    id: "lew",
    name: "Lechwerke (LEW)",
    category: "energie",
    address: "LEW Verteilnetz GmbH\nSchaezlerstr. 3\n86150 Augsburg",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regionalversorger für Bayerisch-Schwaben.",
  },
  {
    id: "enercity",
    name: "enercity",
    category: "energie",
    address: "enercity AG\nIhmeplatz 2\n30449 Hannover",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorger für Hannover.",
  },
  {
    id: "naturstrom2",
    name: "Naturstrom",
    category: "energie",
    address: "NATURSTROM AG\nAchenbachstr. 43\n40237 Düsseldorf",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online", "E-Mail"],
    hinweise: "Ökostrom-Anbieter.",
  },
  {
    id: "prokon",
    name: "Prokon",
    category: "energie",
    address: "Prokon Regenerative Energien eG\nKirkamm 2\n25524 Itzehoe",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Genossenschaft für erneuerbare Energien.",
  },
  
  // ========== ZUSÄTZLICHE BANKING ==========
  {
    id: "targobank2",
    name: "Targobank",
    category: "bank",
    address: "TARGOBANK AG\nKasernenstr. 10\n40213 Düsseldorf",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "In Filiale"],
    hinweise: "Konto vorher ausgleichen und neue Bankverbindung für Daueraufträge hinterlegen.",
  },
  {
    id: "santander2",
    name: "Santander Consumer Bank",
    category: "bank",
    address: "Santander Consumer Bank AG\nSantander-Platz 1\n41061 Mönchengladbach",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kredite haben separate Kündigungsfristen.",
  },
  {
    id: "netbank",
    name: "netbank",
    category: "bank",
    address: "Augsburger Aktienbank AG\nHalderstr. 5\n86150 Augsburg",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online-Bank, Teil der Augsburger Aktienbank.",
  },
  {
    id: "consors",
    name: "Consorsbank",
    category: "bank",
    address: "Consorsbank\nBahnhofstr. 55\n90402 Nürnberg",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Tochter der BNP Paribas.",
  },
  {
    id: "flatex",
    name: "flatex",
    category: "bank",
    address: "flatexDEGIRO Bank AG\nRotfeder-Ring 7\n60327 Frankfurt am Main",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Online-Broker.",
  },
  
  // ========== ZUSÄTZLICHE MOBILFUNK ==========
  {
    id: "simyo2",
    name: "simyo",
    category: "mobilfunk",
    address: "E-Plus Mobilfunk GmbH\nE-Plus-Str. 1\n40472 Düsseldorf",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Discounter im Telefónica-Netz.",
  },
  {
    id: "klarmobil2",
    name: "klarmobil",
    category: "mobilfunk",
    address: "freenet DLS GmbH\nHollerstr. 126\n24782 Büdelsdorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Teil der freenet-Gruppe.",
  },
  {
    id: "simply",
    name: "simply",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Röntgen-Str. 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "1&1 Drillisch Marke.",
  },
  {
    id: "smartmobil",
    name: "smartmobil",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Röntgen-Str. 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "1&1 Drillisch Marke.",
  },
  {
    id: "maxxim",
    name: "maXXim",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Röntgen-Str. 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "1&1 Drillisch Marke.",
  },
  {
    id: "yourfone",
    name: "yourfone",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Röntgen-Str. 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "1&1 Drillisch Marke.",
  },
  
  // ========== ZUSÄTZLICHE VERLAGE & ZEITSCHRIFTEN ==========
  {
    id: "spiegel2",
    name: "DER SPIEGEL",
    category: "verlag",
    address: "SPIEGEL-Verlag Rudolf Augstein GmbH & Co. KG\nEricusspitze 1\n20457 Hamburg",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Print oder Digital-Abo.",
  },
  {
    id: "focus2",
    name: "FOCUS",
    category: "verlag",
    address: "BurdaNews GmbH\nArabellastr. 23\n81925 München",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Nachrichten-Magazin.",
  },
  {
    id: "sueddeutsche2",
    name: "Süddeutsche Zeitung",
    category: "verlag",
    address: "Süddeutsche Zeitung GmbH\nHultschiner Str. 8\n81677 München",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Tageszeitung.",
  },
  {
    id: "faz2",
    name: "Frankfurter Allgemeine Zeitung",
    category: "verlag",
    address: "Frankfurter Allgemeine Zeitung GmbH\nHellerhofstr. 2-4\n60327 Frankfurt am Main",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Tageszeitung.",
  },
  {
    id: "handelsblatt2",
    name: "Handelsblatt",
    category: "verlag",
    address: "Handelsblatt Media Group GmbH & Co. KG\nKasernenstr. 67\n40213 Düsseldorf",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Wirtschaftszeitung.",
  },
  {
    id: "bunte",
    name: "BUNTE",
    category: "verlag",
    address: "Bunte Entertainment Verlag GmbH\nArabellastr. 23\n81925 München",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "People-Magazin.",
  },
  
  // ========== ZUSÄTZLICHE MITGLIEDSCHAFTEN ==========
  {
    id: "adfc",
    name: "ADFC (Fahrradclub)",
    category: "mitgliedschaft",
    address: "Allgemeiner Deutscher Fahrrad-Club e.V.\nMohrenstr. 69\n10117 Berlin",
    kuendigungsfrist: "6 Wochen zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Mitgliedschaft im Fahrrad-Club.",
  },
  {
    id: "nabu",
    name: "NABU",
    category: "mitgliedschaft",
    address: "NABU - Naturschutzbund Deutschland e.V.\nCharitéstr. 3\n10117 Berlin",
    kuendigungsfrist: "Jederzeit zum Jahresende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Naturschutzverband.",
  },
  {
    id: "amnesty",
    name: "Amnesty International",
    category: "mitgliedschaft",
    address: "Amnesty International Deutschland e.V.\nZinnowitzer Str. 8\n10115 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Menschenrechtsorganisation.",
  },
  {
    id: "vdk",
    name: "Sozialverband VdK",
    category: "mitgliedschaft",
    address: "Sozialverband VdK Deutschland e.V.\nWürmseestr. 2a\n82319 Starnberg",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sozialverband.",
  },
  {
    id: "bund",
    name: "BUND",
    category: "mitgliedschaft",
    address: "Bund für Umwelt und Naturschutz Deutschland e.V.\nKaiserstr. 93\n53113 Bonn",
    kuendigungsfrist: "Jederzeit zum Jahresende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Umweltschutzorganisation.",
  },
  
  // ========== ZUSÄTZLICHES SONSTIGES ==========
  {
    id: "mydays2",
    name: "mydays",
    category: "sonstiges",
    address: "mydays GmbH\nAm Münchner Tor 6\n85609 Aschheim",
    kuendigungsfrist: "Keine - Gutscheine",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["E-Mail"],
    hinweise: "Erlebnisgutscheine - in der Regel keine Kündigung nötig.",
  },
  {
    id: "jochen-schweizer",
    name: "Jochen Schweizer",
    category: "sonstiges",
    address: "Jochen Schweizer mydays Group GmbH\nRosenheimer Str. 145e\n81671 München",
    kuendigungsfrist: "Keine - Gutscheine",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["E-Mail"],
    hinweise: "Erlebnisgutscheine.",
  },
  {
    id: "fleurop",
    name: "Fleurop",
    category: "sonstiges",
    address: "Fleurop AG\nRomanshorner Str. 120\n8280 Kreuzlingen, Schweiz",
    kuendigungsfrist: "Keine - Einzelbestellungen",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["E-Mail"],
    hinweise: "Blumenversand.",
  },
  {
    id: "weltbild",
    name: "Weltbild",
    category: "sonstiges",
    address: "Weltbild GmbH & Co. KG\nSteinerne Furt 67\n86167 Augsburg",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["E-Mail", "Schriftlich"],
    hinweise: "Online-Shop für Bücher und Medien.",
  },
  {
    id: "tchibo",
    name: "Tchibo",
    category: "sonstiges",
    address: "Tchibo GmbH\nÜberseering 18\n22297 Hamburg",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Kundenkonto kündigen.",
  },
  {
    id: "aldi-talk2",
    name: "ALDI TALK",
    category: "mobilfunk",
    address: "ALDI TALK\nMedionstr. 1\n45307 Essen",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Prepaid-Mobilfunk von ALDI.",
  },
  {
    id: "netto-connect",
    name: "NettoKOM",
    category: "mobilfunk",
    address: "NettoKOM GmbH\nc/o Telefónica Germany\n40472 Düsseldorf",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Netto Mobilfunk-Discounter.",
  },
  {
    id: "ja-mobil",
    name: "ja! mobil",
    category: "mobilfunk",
    address: "ja! mobil\nc/o REWE Group\n50933 Köln",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "REWE Mobilfunk-Marke.",
  },
  {
    id: "norma-connect",
    name: "NORMA Connect",
    category: "mobilfunk",
    address: "NORMA Connect\nc/o Drillisch Online GmbH\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Norma Mobilfunk-Discounter.",
  },
  {
    id: "pennymobil",
    name: "PENNY mobil",
    category: "mobilfunk",
    address: "PENNY mobil\nc/o REWE Group\n50933 Köln",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Penny Mobilfunk-Marke.",
  },
  {
    id: "lidl-connect2",
    name: "Lidl Connect",
    category: "mobilfunk",
    address: "Lidl Connect\nc/o Vodafone\n40476 Düsseldorf",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Lidl Mobilfunk im Vodafone-Netz.",
  },
  {
    id: "tchibo-mobil",
    name: "TCHIBO mobil",
    category: "mobilfunk",
    address: "Tchibo Mobilfunk GmbH & Co. KG\nÜberseering 18\n22297 Hamburg",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Tchibo Prepaid-Mobilfunk.",
  },

  // ========== ZUSÄTZLICHE BANKEN ==========
  {
    id: "sparkasse-koeln",
    name: "Sparkasse KölnBonn",
    category: "bank",
    address: "Sparkasse KölnBonn\nHahnenstraße 57\n50667 Köln",
    kuendigungsfrist: "Nach Vereinbarung",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Regionale Sparkasse. Kontoführungsgebühren prüfen.",
  },
  {
    id: "berliner-sparkasse",
    name: "Berliner Sparkasse",
    category: "bank",
    address: "Berliner Sparkasse\nAlexanderplatz 2\n10178 Berlin",
    kuendigungsfrist: "Nach Vereinbarung",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Größte Sparkasse Deutschlands.",
  },
  {
    id: "haspa",
    name: "Hamburger Sparkasse (Haspa)",
    category: "bank",
    address: "Haspa\nAdolphsplatz 1\n20457 Hamburg",
    kuendigungsfrist: "Nach Vereinbarung",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Regionale Sparkasse Hamburg.",
  },
  {
    id: "n26-bank",
    name: "N26 Bank",
    category: "bank",
    address: "N26 Bank GmbH\nKlosterstraße 62\n10179 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Digitale Bank. Kündigung über App möglich.",
  },
  {
    id: "revolut",
    name: "Revolut",
    category: "bank",
    address: "Revolut Ltd\n7 Westferry Circus\nLondon E14 4HD, UK",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Internationale Digital-Bank.",
  },
  {
    id: "wise",
    name: "Wise (TransferWise)",
    category: "bank",
    address: "Wise Payments Limited\nTea Building, 56 Shoreditch High St\nLondon E1 6JJ, UK",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Multi-Währungs-Konto.",
  },
  {
    id: "bunq",
    name: "bunq",
    category: "bank",
    address: "bunq B.V.\nNaritaweg 165\n1043 BW Amsterdam, Niederlande",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Nachhaltige Digital-Bank.",
  },

  // ========== ZUSÄTZLICHE VERSICHERUNGEN ==========
  {
    id: "axa-lebensversicherung",
    name: "AXA Lebensversicherung",
    category: "versicherung",
    address: "AXA Lebensversicherung AG\nColonia-Allee 10-20\n51067 Köln",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Lebensversicherung. Steuerliche Aspekte beachten.",
  },
  {
    id: "deutsche-familienversicherung",
    name: "Deutsche Familienversicherung (DFV)",
    category: "versicherung",
    address: "DFV Deutsche Familienversicherung AG\nReuterweg 47\n60323 Frankfurt",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Digitale Versicherung.",
  },
  {
    id: "helvetia",
    name: "Helvetia Versicherung",
    category: "versicherung",
    address: "Helvetia Schweizerische Versicherungsgesellschaft AG\nBerliner Str. 56-58\n60311 Frankfurt",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Schweizer Versicherungskonzern.",
  },
  {
    id: "wuerttembergische2",
    name: "Württembergische Versicherung",
    category: "versicherung",
    address: "Württembergische Versicherung AG\nGutenbergstraße 30\n70176 Stuttgart",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Traditionsversicherer aus Baden-Württemberg.",
  },
  {
    id: "signal-iduna2",
    name: "SIGNAL IDUNA",
    category: "versicherung",
    address: "SIGNAL IDUNA Gruppe\nJoseph-Scherer-Straße 3\n44139 Dortmund",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Große Versicherungsgruppe.",
  },

  // ========== ZUSÄTZLICHE STREAMING ==========
  {
    id: "sky-ticket",
    name: "Sky Ticket",
    category: "streaming",
    address: "Sky Deutschland GmbH\nMedienallee 26\n85774 Unterföhring",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Flexible Streaming-Option von Sky.",
  },
  {
    id: "joyn-plus",
    name: "Joyn PLUS+",
    category: "streaming",
    address: "Joyn GmbH\nMedienallee 4\n85774 Unterföhring",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "ProSieben/Sat.1 Streaming-Dienst.",
  },
  {
    id: "rtl-plus",
    name: "RTL+",
    category: "streaming",
    address: "RTL Deutschland GmbH\nPicassoplatz 1\n50679 Köln",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Streaming von RTL-Inhalten.",
  },
  {
    id: "paramount-plus2",
    name: "Paramount+",
    category: "streaming",
    address: "Paramount Global\n1515 Broadway\nNew York, NY 10036, USA",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "US-Streaming mit Star Trek etc.",
  },
  {
    id: "mubi2",
    name: "MUBI",
    category: "streaming",
    address: "MUBI Inc.\n200 Aldersgate\nLondon EC1A 4HD, UK",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Arthouse & Independent Filme.",
  },
  {
    id: "crunchyroll3",
    name: "Crunchyroll",
    category: "streaming",
    address: "Crunchyroll LLC\n835 Market St\nSan Francisco, CA 94103, USA",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Anime-Streaming.",
  },

  // ========== ZUSÄTZLICHE FITNESS ==========
  {
    id: "fitness-first2",
    name: "Fitness First",
    category: "fitness",
    address: "Fitness First Germany GmbH\nHanauer Landstraße 155-161\n60314 Frankfurt",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Premium-Fitnesskette.",
  },
  {
    id: "clever-fit2",
    name: "clever fit",
    category: "fitness",
    address: "(Adresse Ihres Studios eintragen)",
    kuendigungsfrist: "2 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Budget-Fitnesskette. Studio-Adresse variiert.",
  },
  {
    id: "kieser-training2",
    name: "Kieser Training",
    category: "fitness",
    address: "(Adresse Ihres Studios eintragen)",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "6 Monate",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Krafttraining-Spezialist.",
  },
  {
    id: "easyfitness",
    name: "easyFitness",
    category: "fitness",
    address: "(Adresse Ihres Studios eintragen)",
    kuendigungsfrist: "2 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Discounter-Fitnesskette.",
  },
  {
    id: "mrs-sporty3",
    name: "Mrs.Sporty",
    category: "fitness",
    address: "(Adresse Ihres Studios eintragen)",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "3 Monate",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Frauenfitness-Studio.",
  },

  // ========== ZUSÄTZLICHE INTERNET/DSL ==========
  {
    id: "pyur3",
    name: "PYUR",
    category: "internet",
    address: "Tele Columbus AG\nKaiserin-Augusta-Allee 108\n10553 Berlin",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kabel-Internet.",
  },
  {
    id: "easybell2",
    name: "easybell",
    category: "internet",
    address: "easybell GmbH\nReinhardtstraße 58\n10117 Berlin",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Flexibler DSL-Anbieter.",
  },
  {
    id: "m-net2",
    name: "M-net",
    category: "internet",
    address: "M-net Telekommunikations GmbH\nEmmystraße 10\n85622 Feldkirchen",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regionaler Glasfaseranbieter (Bayern).",
  },
  {
    id: "netcologne3",
    name: "NetCologne",
    category: "internet",
    address: "NetCologne Gesellschaft für Telekommunikation mbH\nAm Coloneum 9\n50829 Köln",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regionaler Anbieter Köln/Region.",
  },

  // ========== ZUSÄTZLICHE ENERGIE ==========
  {
    id: "naturstrom3",
    name: "Naturstrom",
    category: "energie",
    address: "NATURSTROM AG\nAchenbachstraße 43\n40238 Düsseldorf",
    kuendigungsfrist: "4 Wochen",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Ökostromanbieter.",
  },
  {
    id: "polarstern",
    name: "Polarstern Energie",
    category: "energie",
    address: "Polarstern GmbH\nLindwurmstraße 88\n80337 München",
    kuendigungsfrist: "4 Wochen",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Nachhaltiger Energieversorger.",
  },
  {
    id: "lichtblick2",
    name: "LichtBlick",
    category: "energie",
    address: "LichtBlick SE\nKlostertor 1\n20097 Hamburg",
    kuendigungsfrist: "4 Wochen",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Größter unabhängiger Ökostromanbieter.",
  },
  {
    id: "enercity2",
    name: "enercity",
    category: "energie",
    address: "enercity AG\nIhmeplatz 2\n30449 Hannover",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Stadtwerke Hannover.",
  },
  {
    id: "swm-muenchen",
    name: "Stadtwerke München (SWM)",
    category: "energie",
    address: "Stadtwerke München GmbH\nEmmy-Noether-Straße 2\n80992 München",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Kommunales Versorgungsunternehmen München.",
  },

  // ========== ZUSÄTZLICHE VERLAGE/ZEITSCHRIFTEN ==========
  {
    id: "der-spiegel",
    name: "Der Spiegel (Abo)",
    category: "verlag",
    address: "SPIEGEL-Verlag Rudolf Augstein GmbH & Co. KG\nEricusspitze 1\n20457 Hamburg",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Nachrichtenmagazin.",
  },
  {
    id: "focus3",
    name: "Focus (Abo)",
    category: "verlag",
    address: "FOCUS Magazin Verlag GmbH\nArabellastraße 23\n81925 München",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Nachrichtenmagazin.",
  },
  {
    id: "stern2",
    name: "Stern (Abo)",
    category: "verlag",
    address: "Gruner + Jahr GmbH\nAm Baumwall 11\n20459 Hamburg",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Illustrierte.",
  },
  {
    id: "geo",
    name: "GEO (Abo)",
    category: "verlag",
    address: "Gruner + Jahr GmbH\nAm Baumwall 11\n20459 Hamburg",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Wissenschaftsmagazin.",
  },
  {
    id: "auto-motor-sport",
    name: "auto motor und sport (Abo)",
    category: "verlag",
    address: "Motor Presse Stuttgart GmbH & Co. KG\nLeuschnerstraße 1\n70174 Stuttgart",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Automobilmagazin.",
  },

  // ========== ZUSÄTZLICHE SONSTIGE ==========
  {
    id: "adac2",
    name: "ADAC (Mitgliedschaft)",
    category: "mitgliedschaft",
    address: "ADAC e.V.\nHansastraße 19\n80686 München",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Automobilclub. Mitgliedsbeiträge steuerlich absetzbar (teilweise).",
  },
  {
    id: "ace",
    name: "ACE Auto Club Europa",
    category: "mitgliedschaft",
    address: "ACE Auto Club Europa e.V.\nSchmidener Straße 227\n70374 Stuttgart",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Alternative zum ADAC.",
  },
  {
    id: "avd",
    name: "AvD (Automobilclub von Deutschland)",
    category: "mitgliedschaft",
    address: "Automobilclub von Deutschland e.V.\nLyoner Straße 16\n60528 Frankfurt",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Traditionsreicher Automobilclub.",
  },
  {
    id: "nabu2",
    name: "NABU (Naturschutzbund)",
    category: "mitgliedschaft",
    address: "NABU-Bundesverband\nCharitéstraße 3\n10117 Berlin",
    kuendigungsfrist: "Zum Jahresende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Umweltschutzorganisation.",
  },
  {
    id: "greenpeace",
    name: "Greenpeace (Fördermitgliedschaft)",
    category: "mitgliedschaft",
    address: "Greenpeace e.V.\nHongkongstraße 10\n20457 Hamburg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Umweltorganisation. Spenden steuerlich absetzbar.",
  },
  {
    id: "wwf",
    name: "WWF (World Wide Fund For Nature)",
    category: "mitgliedschaft",
    address: "WWF Deutschland\nReinhardtstraße 18\n10117 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Naturschutzorganisation.",
  },
  {
    id: "bahncard-25",
    name: "BahnCard 25",
    category: "sonstiges",
    address: "DB Vertrieb GmbH\nEuropaplatz 1\n10557 Berlin",
    kuendigungsfrist: "6 Wochen vor Ablauf",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Automatische Verlängerung verhindern!",
  },
  {
    id: "bahncard-50",
    name: "BahnCard 50",
    category: "sonstiges",
    address: "DB Vertrieb GmbH\nEuropaplatz 1\n10557 Berlin",
    kuendigungsfrist: "6 Wochen vor Ablauf",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Automatische Verlängerung verhindern!",
  },
  {
    id: "bahncard-100",
    name: "BahnCard 100",
    category: "sonstiges",
    address: "DB Vertrieb GmbH\nEuropaplatz 1\n10557 Berlin",
    kuendigungsfrist: "6 Wochen vor Ablauf",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Automatische Verlängerung verhindern!",
  },
  {
    id: "spotify-premium",
    name: "Spotify Premium",
    category: "streaming",
    address: "Spotify AB\nRegerings gatan 19\n111 53 Stockholm, Schweden",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Musik-Streaming. Kündigung über Account-Einstellungen.",
  },
  {
    id: "apple-music",
    name: "Apple Music",
    category: "streaming",
    address: "Apple Distribution International Ltd.\nHollyhill Industrial Estate\nHollyhill, Cork, Irland",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über iTunes/Apple-ID-Einstellungen.",
  },
  {
    id: "youtube-premium2",
    name: "YouTube Premium",
    category: "streaming",
    address: "Google Ireland Limited\nGordon House, Barrow Street\nDublin 4, Irland",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über Google-Konto.",
  },
  {
    id: "audible2",
    name: "Audible",
    category: "streaming",
    address: "Audible GmbH\nAuer-Welsbach-Straße 47\n81379 München",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Hörbuch-Abo. Kündigung über Website.",
  },
  {
    id: "blinkist",
    name: "Blinkist",
    category: "streaming",
    address: "Blinks Labs GmbH\nSonnenallee 223\n12059 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Buchzusammenfassungen-App.",
  },

  // ========== JOB & KARRIERE ==========
  {
    id: "stepstone",
    name: "StepStone",
    category: "arbeit",
    address: "StepStone Deutschland GmbH\nBonnstrasse 430\n40589 Duesseldorf",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Premium-Stellenanzeigen und Abonnements online kuendbar unter stepstone.de/account.",
  },
  {
    id: "indeed",
    name: "Indeed",
    category: "arbeit",
    address: "Indeed Ireland Operations Ltd.\n124 St. Stephen's Green\nDublin 2, Irland",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Konto-Einstellungen auf indeed.com.",
  },
  {
    id: "linkedin-jobs",
    name: "LinkedIn Jobs / Recruiter",
    category: "arbeit",
    address: "LinkedIn Ireland Unlimited Company\nWilton Plaza\nDublin 2, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Job-Postings und Recruiter-Pakete ueber linkedin.com Kontoeinstellungen kuendbar.",
  },
  {
    id: "xing-jobs",
    name: "XING Jobs / TalentManager",
    category: "arbeit",
    address: "New Work SE\nDammtorstrasse 30\n20354 Hamburg",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber xing.com Kontoeinstellungen.",
  },
  {
    id: "monster",
    name: "Monster",
    category: "arbeit",
    address: "Monster Worldwide Deutschland GmbH\nNymphenburger Str. 3\n80335 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto und Abonnements ueber monster.de kuendbar.",
  },
  {
    id: "arbeitsagentur",
    name: "Bundesagentur fuer Arbeit (Jobprofil)",
    category: "arbeit",
    address: "Bundesagentur fuer Arbeit\nRegensburger Strasse 104\n90478 Nuernberg",
    kuendigungsfrist: "Keine",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kostenloses Jobportal. Bewerberprofil jederzeit loeschbar unter arbeitsagentur.de.",
  },
  {
    id: "hokify",
    name: "hokify",
    category: "arbeit",
    address: "hokify GmbH\nMariahilfer Strasse 50\n1070 Wien, Oesterreich",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Mobile Job-Plattform. Konto ueber App-Einstellungen loeschbar.",
  },
  {
    id: "jobware",
    name: "Jobware",
    category: "arbeit",
    address: "Jobware Online-Service GmbH\nAm Stadtholz 24\n33104 Paderborn",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Stellenanzeigen-Portal fuer Fach- und Fuehrungskraefte.",
  },
]