export type CompanyCategory =
  | "telekommunikation"
  | "versicherung"
  | "energie"
  | "fitness"
  | "streaming"
  | "bank"
  | "internet"
  | "mobilfunk"
  | "verlag"
  | "mitgliedschaft"
  | "arbeit"
  | "sonstiges"

export interface Company {
  id: string
  name: string
  category: CompanyCategory
  address: string
  kuendigungsfrist: string
  mindestlaufzeit: string
  kuendigungsart: string[]
  hinweise: string
}

export const CATEGORY_LABELS: Record<CompanyCategory, string> = {
  telekommunikation: "Telekommunikation",
  versicherung: "Versicherung",
  energie: "Energie",
  fitness: "Fitness & Sport",
  streaming: "Streaming & Medien",
  bank: "Bank & Finanzen",
  internet: "Internet & DSL",
  mobilfunk: "Mobilfunk",
  verlag: "Verlag & Zeitschriften",
  mitgliedschaft: "Mitgliedschaft & Verein",
  arbeit: "Job & Karriere",
  sonstiges: "Sonstiges",
}

export const companies: Company[] = [
  // ========== TELEKOMMUNIKATION & INTERNET ==========
  {
    id: "telekom",
    name: "Deutsche Telekom",
    category: "telekommunikation",
    address: "Telekom Deutschland GmbH\nKundenservice\n53171 Bonn",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online-Kündigung über das Kundencenter möglich.",
  },
  {
    id: "vodafone",
    name: "Vodafone",
    category: "telekommunikation",
    address: "Vodafone GmbH\nKundenbetreuung\n40549 Düsseldorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Fax", "Online"],
    hinweise: "Fax: 0211 533 1612. Online-Kündigung über MeinVodafone.",
  },
  {
    id: "o2",
    name: "O2 / Telefónica",
    category: "telekommunikation",
    address: "Telefónica Germany GmbH & Co. OHG\nKundenbetreuung\n90345 Nürnberg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kündigung per Brief oder über Mein O2 online.",
  },
  {
    id: "1und1",
    name: "1&1",
    category: "telekommunikation",
    address: "1&1 Telecom GmbH\nElgendorfer Straße 57\n56410 Montabaur",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kündigung am besten per Einschreiben senden.",
  },
  {
    id: "freenet",
    name: "freenet",
    category: "telekommunikation",
    address: "freenet AG\nHollerstraße 126\n24782 Büdelsdorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Verschiedene Marken (mobilcom-debitel, klarmobil). Vertrag prüfen!",
  },
  {
    id: "mobilcom-debitel",
    name: "mobilcom-debitel",
    category: "telekommunikation",
    address: "freenet AG\nHollerstraße 126\n24782 Büdelsdorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehört zur freenet-Gruppe. Kündigung auch online im Kundencenter.",
  },
  {
    id: "unitymedia",
    name: "Unitymedia / Vodafone Kabel",
    category: "internet",
    address: "Vodafone GmbH\nKundenbetreuung\n40549 Düsseldorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Nach Übernahme durch Vodafone: Kündigung an Vodafone richten.",
  },
  {
    id: "pyur",
    name: "PŸUR / Tele Columbus",
    category: "internet",
    address: "Tele Columbus AG\nKaiserin-Augusta-Allee 108\n10553 Berlin",
    kuendigungsfrist: "1-3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kabel-Internet und TV-Anbieter. Kündigung per Einschreiben empfohlen.",
  },
  {
    id: "easybell",
    name: "easybell",
    category: "internet",
    address: "easybell GmbH\nReinhardtstraße 58\n10117 Berlin",
    kuendigungsfrist: "14 Tage zum Monatsende",
    mindestlaufzeit: "Keine (monatlich kündbar)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Monatlich kündbar. Kündigung über das Kundenportal.",
  },
  {
    id: "m-net",
    name: "M-net",
    category: "internet",
    address: "M-net Telekommunikations GmbH\nEmmy-Noether-Str. 2\n80992 München",
    kuendigungsfrist: "1-3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regionaler Glasfaseranbieter in Bayern.",
  },
  {
    id: "netcologne",
    name: "NetCologne",
    category: "internet",
    address: "NetCologne Gesellschaft für Telekommunikation mbH\nAm Coloneum 9\n50829 Köln",
    kuendigungsfrist: "1-3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online", "Fax"],
    hinweise: "Regionaler Anbieter für Köln und Umgebung.",
  },
  {
    id: "ewe",
    name: "EWE Tel / osnatel",
    category: "telekommunikation",
    address: "EWE TEL GmbH\nCloppenburger Str. 310\n26133 Oldenburg",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regional in Norddeutschland verfügbar. Zuständig auch für osnatel.",
  },

  // ========== MOBILFUNK ==========
  {
    id: "congstar",
    name: "congstar",
    category: "mobilfunk",
    address: "congstar GmbH\nKundenservice\n50969 Köln",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate (Allnet Flat), keine (Prepaid)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Prepaid-Tarife sind jederzeit kündbar.",
  },
  {
    id: "aldi-talk",
    name: "ALDI TALK",
    category: "mobilfunk",
    address: "Medion AG\nAm Zehnthof 77\n45307 Essen",
    kuendigungsfrist: "Keine (Prepaid)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail", "Online"],
    hinweise: "Prepaid-Karte jederzeit kündbar. E-Mail: kundenservice@alditalk.de",
  },
  {
    id: "lidl-connect",
    name: "Lidl Connect",
    category: "mobilfunk",
    address: "Lidl Connect Kundenbetreuung\nPostfach 10 01 53\n40001 Düsseldorf",
    kuendigungsfrist: "Keine (Prepaid)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Prepaid-Karte. Kündigung jederzeit möglich.",
  },
  {
    id: "klarmobil",
    name: "klarmobil",
    category: "mobilfunk",
    address: "klarmobil GmbH\nHollerstraße 126\n24782 Büdelsdorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate (Laufzeitvertrag)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehört zur freenet-Gruppe.",
  },
  {
    id: "blau",
    name: "Blau / simyo",
    category: "mobilfunk",
    address: "Blau Service GmbH\n90345 Nürnberg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate / monatlich kündbar",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehört zum O2/Telefónica-Netz. Simyo ist ebenfalls hier eingegliedert.",
  },
  {
    id: "otelo",
    name: "otelo",
    category: "mobilfunk",
    address: "Vodafone GmbH\n40549 Düsseldorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Discount-Marke von Vodafone.",
  },
  {
    id: "winSIM",
    name: "winSIM",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Röntgen-Straße 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate / monatlich kündbar",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehört zur Drillisch/1&1-Gruppe.",
  },
  {
    id: "premiumsim",
    name: "PremiumSIM",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Röntgen-Straße 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate / monatlich kündbar",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Drillisch-Marke.",
  },
  {
    id: "fraenk",
    name: "fraenk",
    category: "mobilfunk",
    address: "fraenk (Telekom)\n53171 Bonn",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Monatlich kündbar über die fraenk-App.",
  },
  {
    id: "tchibo-mobil",
    name: "TCHIBO mobil",
    category: "mobilfunk",
    address: "Tchibo Mobilfunk GmbH & Co. KG\nÜberseering 18\n22297 Hamburg",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Tchibo Prepaid-Mobilfunk.",
  },
  {
    id: "netto-connect",
    name: "NettoKOM",
    category: "mobilfunk",
    address: "NettoKOM GmbH\nc/o Telefónica Germany\n40472 Düsseldorf",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Netto Mobilfunk-Discounter.",
  },
  {
    id: "ja-mobil",
    name: "ja! mobil",
    category: "mobilfunk",
    address: "ja! mobil\nc/o REWE Group\n50933 Köln",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "REWE Mobilfunk-Marke.",
  },
  {
    id: "norma-connect",
    name: "NORMA Connect",
    category: "mobilfunk",
    address: "NORMA Connect\nc/o Drillisch Online GmbH\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Norma Mobilfunk-Discounter.",
  },
  {
    id: "pennymobil",
    name: "PENNY mobil",
    category: "mobilfunk",
    address: "PENNY mobil\nc/o REWE Group\n50933 Köln",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Penny Mobilfunk-Marke.",
  },
  {
    id: "simply",
    name: "simply",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Röntgen-Str. 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "1&1 Drillisch Marke.",
  },
  {
    id: "smartmobil",
    name: "smartmobil",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Röntgen-Str. 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "1&1 Drillisch Marke.",
  },
  {
    id: "maxxim",
    name: "maXXim",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Röntgen-Str. 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "1&1 Drillisch Marke.",
  },
  {
    id: "yourfone",
    name: "yourfone",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Röntgen-Str. 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "1&1 Drillisch Marke.",
  },

  // ========== VERSICHERUNG ==========
  {
    id: "allianz",
    name: "Allianz Versicherung",
    category: "versicherung",
    address: "Allianz Versicherungs-AG\n10900 Berlin",
    kuendigungsfrist: "1-3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkündigungsrecht bei Beitragserhöhung. Vertragsnummer angeben!",
  },
  {
    id: "huk-coburg",
    name: "HUK-COBURG / HUK24",
    category: "versicherung",
    address: "HUK-COBURG\nBahnhofsplatz\n96450 Coburg",
    kuendigungsfrist: "1 Monat zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kfz-Versicherung: Stichtag ist oft der 30. November. HUK24 am besten online kündigen.",
  },
  {
    id: "ergo",
    name: "ERGO Versicherung",
    category: "versicherung",
    address: "ERGO Versicherung AG\n40198 Düsseldorf",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer und Versicherungsscheinnummer im Schreiben angeben.",
  },
  {
    id: "axa",
    name: "AXA Versicherung",
    category: "versicherung",
    address: "AXA Konzern AG\nColonia-Allee 10-20\n51067 Köln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Lebensversicherung hat eigene Fristen (AXA Lebensversicherung AG).",
  },
  {
    id: "debeka",
    name: "Debeka",
    category: "versicherung",
    address: "Debeka\nFerdinand-Sauerbruch-Straße 18\n56073 Koblenz",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Krankenversicherung: Besondere Regelungen beachten!",
  },
  {
    id: "generali",
    name: "Generali Versicherung",
    category: "versicherung",
    address: "Generali Deutschland AG\nAdenauerring 7\n81737 München",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkündigungsrecht bei Beitragserhöhung.",
  },
  {
    id: "zurich",
    name: "Zurich Versicherung",
    category: "versicherung",
    address: "Zurich Gruppe Deutschland\nSolmsstraße 27-37\n60486 Frankfurt am Main",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer unbedingt angeben.",
  },
  {
    id: "dkv",
    name: "DKV (Deutsche Krankenversicherung)",
    category: "versicherung",
    address: "DKV AG\n50594 Köln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "PKV-Kündigung: Nachweis der Anschlussversicherung erforderlich!",
  },
  {
    id: "lvm",
    name: "LVM Versicherung",
    category: "versicherung",
    address: "LVM Versicherung\nKolde-Ring 21\n48151 Münster",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kündigung über den Vertreter oder per Einschreiben.",
  },
  {
    id: "devk",
    name: "DEVK Versicherung",
    category: "versicherung",
    address: "DEVK Versicherungen\nRiehler Straße 190\n50735 Köln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Sonderkündigungsrecht nach Schadensfall.",
  },
  {
    id: "wuerttembergische",
    name: "Württembergische Versicherung",
    category: "versicherung",
    address: "Württembergische Versicherung AG\nGutenbergstraße 30\n70176 Stuttgart",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer und Sparte angeben.",
  },
  {
    id: "gothaer",
    name: "Gothaer Versicherung",
    category: "versicherung",
    address: "Gothaer Allgemeine Versicherung AG\n50598 Köln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Per Einschreiben senden.",
  },
  {
    id: "signal-iduna",
    name: "SIGNAL IDUNA",
    category: "versicherung",
    address: "SIGNAL IDUNA Gruppe\nJoseph-Scherer-Straße 3\n44139 Dortmund",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer angeben.",
  },
  {
    id: "hdi",
    name: "HDI Versicherung",
    category: "versicherung",
    address: "HDI Versicherung AG\n30659 Hannover",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Einschreiben empfohlen.",
  },
  {
    id: "nuernberger",
    name: "Nürnberger Versicherung",
    category: "versicherung",
    address: "Nürnberger Versicherung AG\n90334 Nürnberg",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertrag und Versicherungsscheinnummer angeben.",
  },
  {
    id: "r-und-v",
    name: "R+V Versicherung",
    category: "versicherung",
    address: "R+V Allgemeine Versicherung AG\nRaiffeisenplatz 1\n65189 Wiesbaden",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Genossenschaftliche Versicherung. Berater kontaktieren empfohlen.",
  },
  {
    id: "cosmos-direkt",
    name: "CosmosDirekt",
    category: "versicherung",
    address: "CosmosDirekt\nHalbergstraße 50-60\n66121 Saarbrücken",
    kuendigungsfrist: "1-3 Monate zum Vertragsende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Sonderkündigungsrecht bei Beitragserhöhung innerhalb eines Monats.",
  },
  {
    id: "provinzial",
    name: "Provinzial Versicherung",
    category: "versicherung",
    address: "Provinzial Holding AG\nProvinzialplatz 1\n40215 Düsseldorf",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Regionale Unterschiede bei Ansprechpartnern möglich (Rheinland/Nordwest).",
  },
  {
    id: "vhv",
    name: "VHV Versicherung",
    category: "versicherung",
    address: "VHV Allgemeine Versicherung AG\nVHV-Platz 1\n30177 Hannover",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Spezialisiert auf Autoversicherungen.",
  },
  {
    id: "basler",
    name: "Basler Versicherungen",
    category: "versicherung",
    address: "Basler Versicherungen\nBasler Str. 4\n61352 Bad Homburg",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sachversicherungen.",
  },
  {
    id: "petolo",
    name: "Petolo Tierkrankenversicherung",
    category: "versicherung",
    address: "dentolo Deutschland GmbH (Petolo)\nTorstraße 33\n10119 Berlin",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Sonderkündigungsrecht bei Beitragserhöhung.",
  },
  {
    id: "clark-versicherung",
    name: "Clark Versicherung",
    category: "versicherung",
    address: "Clark Germany GmbH\nGoethestraße 10\n60313 Frankfurt am Main",
    kuendigungsfrist: "Abhängig vom Vertrag",
    mindestlaufzeit: "Abhängig vom Vertrag",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Clark als Makler kündigt auf Wunsch bei der Versicherung.",
  },
  {
    id: "friendsurance",
    name: "Friendsurance",
    category: "versicherung",
    address: "Friendsurance Deutschland GmbH\nAltenburger Str. 44\n04275 Leipzig",
    kuendigungsfrist: "Abhängig vom Vertrag",
    mindestlaufzeit: "Abhängig vom Versicherungsvertrag",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Kündigung der Friendsurance-Mitgliedschaft und/oder des Versicherungsvertrags separat.",
  },
  {
    id: "deutsche-familienversicherung",
    name: "Deutsche Familienversicherung (DFV)",
    category: "versicherung",
    address: "DFV Deutsche Familienversicherung AG\nReuterweg 47\n60323 Frankfurt",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Digitale Versicherung.",
  },
  {
    id: "helvetia",
    name: "Helvetia Versicherung",
    category: "versicherung",
    address: "Helvetia Schweizerische Versicherungsgesellschaft AG\nBerliner Str. 56-58\n60311 Frankfurt",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Schweizer Versicherungskonzern.",
  },
  {
    id: "gkv",
    name: "Gesetzliche Krankenkasse (AOK, TK, BARMER, DAK...)",
    category: "versicherung",
    address: "(Adresse Ihrer zuständigen Krankenkasse eintragen)",
    kuendigungsfrist: "2 Monate zum Monatsende",
    mindestlaufzeit: "12 Monate bei Neuwahl",
    kuendigungsart: ["Schriftlich"],
    hinweise: "GKV-Wechsel: Neue Kasse übernimmt ab 2021 meist automatisch die Kündigung!",
  },

  // ========== ENERGIE ==========
  {
    id: "eon",
    name: "E.ON Energie",
    category: "energie",
    address: "E.ON Energie Deutschland GmbH\nPostfach 1475\n84001 Landshut",
    kuendigungsfrist: "1 Monat / 14 Tage (Grundversorgung)",
    mindestlaufzeit: "Vertragsabhängig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "In der Grundversorgung: 2 Wochen Kündigungsfrist.",
  },
  {
    id: "vattenfall",
    name: "Vattenfall",
    category: "energie",
    address: "Vattenfall Europe Sales GmbH\nPostfach 73 91 24\n13092 Berlin",
    kuendigungsfrist: "1 Monat / 14 Tage (Grundversorgung)",
    mindestlaufzeit: "Vertragsabhängig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorgung: 2 Wochen Frist. Bei Umzug Sonderkündigungsrecht.",
  },
  {
    id: "rwe",
    name: "RWE / innogy",
    category: "energie",
    address: "RWE AG\nHuyssenallee 2\n45128 Essen",
    kuendigungsfrist: "Vertragsabhängig",
    mindestlaufzeit: "Vertragsabhängig",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsbedingungen im Einzelfall prüfen.",
  },
  {
    id: "enbw",
    name: "EnBW",
    category: "energie",
    address: "EnBW Energie Baden-Württemberg AG\nPostfach 10 06 20\n76236 Karlsruhe",
    kuendigungsfrist: "1 Monat / 14 Tage (Grundversorgung)",
    mindestlaufzeit: "Vertragsabhängig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorgung jederzeit mit 2 Wochen Frist kündbar.",
  },
  {
    id: "stadtwerke-muenchen",
    name: "Stadtwerke München (SWM)",
    category: "energie",
    address: "Stadtwerke München GmbH\nEmmy-Noether-Str. 2\n80992 München",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine (Grundversorgung)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kommunales Versorgungsunternehmen München. Grundversorgung: 2 Wochen Frist.",
  },
  {
    id: "yello",
    name: "Yello Strom",
    category: "energie",
    address: "Yello Strom GmbH\nPostfach 10 32 61\n50472 Köln",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Tochter der EnBW.",
  },
  {
    id: "eprimo",
    name: "eprimo",
    category: "energie",
    address: "eprimo GmbH\nFlughafenstraße 20\n63263 Neu-Isenburg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Tochterunternehmen von E.ON. Online-Kündigung möglich.",
  },
  {
    id: "lichtblick",
    name: "LichtBlick",
    category: "energie",
    address: "LichtBlick SE\nKlostertor 1\n20097 Hamburg",
    kuendigungsfrist: "4 Wochen zum Vertragsende",
    mindestlaufzeit: "Keine oder 12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Größter unabhängiger Ökostrom-Anbieter.",
  },
  {
    id: "naturstrom",
    name: "NATURSTROM",
    category: "energie",
    address: "NATURSTROM AG\nAchenbachstraße 43\n40237 Düsseldorf",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Ökostrom-Anbieter.",
  },
  {
    id: "envia-m",
    name: "enviaM",
    category: "energie",
    address: "envia Mitteldeutsche Energie AG\nPostfach 1560\n09004 Chemnitz",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "Vertragsabhängig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regionalversorger für Mitteldeutschland.",
  },
  {
    id: "swb-energie",
    name: "swb Energie",
    category: "energie",
    address: "swb AG\nTheodor-Heuss-Allee 20\n28215 Bremen",
    kuendigungsfrist: "6 Wochen zum Vertragsende (Sondertarife)",
    mindestlaufzeit: "Je nach Tarif",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorgung: 2 Wochen Kündigungsfrist.",
  },
  {
    id: "mainova",
    name: "Mainova",
    category: "energie",
    address: "Mainova AG\nSolmsstraße 38\n60486 Frankfurt am Main",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate (Sondertarife)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regionalversorger für Frankfurt.",
  },
  {
    id: "entega",
    name: "ENTEGA",
    category: "energie",
    address: "ENTEGA Plus GmbH\nPostfach 11 05 52\n64220 Darmstadt",
    kuendigungsfrist: "6 Wochen zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Ökostrom- und Ökogas-Anbieter aus Südhessen.",
  },
  {
    id: "rheinenergie",
    name: "RheinEnergie",
    category: "energie",
    address: "RheinEnergie AG\nParkgürtel 24\n50823 Köln",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine (Grundversorgung)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorger für Köln.",
  },
  {
    id: "lew",
    name: "Lechwerke (LEW)",
    category: "energie",
    address: "LEW Verteilnetz GmbH\nSchaezlerstraße 3\n86150 Augsburg",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regionalversorger für Bayerisch-Schwaben.",
  },
  {
    id: "enercity",
    name: "enercity",
    category: "energie",
    address: "enercity AG\nIhmeplatz 2\n30449 Hannover",
    kuendigungsfrist: "1 Monat zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorger für Hannover.",
  },
  {
    id: "prokon",
    name: "Prokon",
    category: "energie",
    address: "Prokon Regenerative Energien eG\nKirkamm 2\n25524 Itzehoe",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Genossenschaft für erneuerbare Energien.",
  },
  {
    id: "polarstern",
    name: "Polarstern Energie",
    category: "energie",
    address: "Polarstern GmbH\nLindwurmstraße 88\n80337 München",
    kuendigungsfrist: "4 Wochen",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Nachhaltiger Energieversorger.",
  },

  // ========== FITNESS & SPORT ==========
  {
    id: "mcfit",
    name: "McFIT / John Reed",
    category: "fitness",
    address: "RSG Group GmbH\nTannenberg 4\n96132 Schlüsselfeld",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online-Kündigung über den Self-Service am einfachsten.",
  },
  {
    id: "fitx",
    name: "FitX",
    category: "fitness",
    address: "FitX Deutschland GmbH\nÜberseering 33b\n22297 Hamburg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online über den Selfservice-Bereich möglich.",
  },
  {
    id: "fitness-first",
    name: "Fitness First",
    category: "fitness",
    address: "Fitness First Germany GmbH\nHanauer Landstraße 148a\n60314 Frankfurt am Main",
    kuendigungsfrist: "1-3 Monate zum Vertragsende",
    mindestlaufzeit: "12-24 Monate",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Premium-Fitnesskette.",
  },
  {
    id: "clever-fit",
    name: "clever fit",
    category: "fitness",
    address: "(Adresse Ihres lokalen Studios eintragen)",
    kuendigungsfrist: "1-3 Monate zum Vertragsende",
    mindestlaufzeit: "12-24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Franchise-Unternehmen. Kündigung MUSS an das jeweilige Studio gesendet werden.",
  },
  {
    id: "urban-sports",
    name: "Urban Sports Club",
    category: "fitness",
    address: "Urban Sports GmbH\nMichaelkirchstraße 20\n10179 Berlin",
    kuendigungsfrist: "1 Monat (bei Flex-Tarifen)",
    mindestlaufzeit: "Keine (bei Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über die App oder das Online-Konto.",
  },
  {
    id: "bodystreet",
    name: "Bodystreet (EMS-Training)",
    category: "fitness",
    address: "(Adresse Ihres lokalen Bodystreet Studios eintragen)",
    kuendigungsfrist: "Vertragsabhängig (meist 3 Monate)",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "EMS-Studio. Kündigung direkt an das Franchise-Studio senden.",
  },
  {
    id: "kieser-training",
    name: "Kieser Training",
    category: "fitness",
    address: "(Adresse Ihres lokalen Studios eintragen)",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "6-12 Monate",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Krafttraining-Studios.",
  },
  {
    id: "mrs-sporty",
    name: "Mrs.Sporty",
    category: "fitness",
    address: "(Adresse Ihres lokalen Studios eintragen)",
    kuendigungsfrist: "1-3 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Frauenfitness-Studio. Kündigung an das jeweilige Studio richten.",
  },
  {
    id: "injoy",
    name: "INJOY Fitness",
    category: "fitness",
    address: "(Adresse Ihres lokalen Studios eintragen)",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "12–24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Franchise-Unternehmen – Kündigung direkt an das Studio.",
  },
  {
    id: "hansefit",
    name: "Hansefit (Firmenfitness)",
    category: "fitness",
    address: "Hansefit GmbH & Co. KG\nDurchschnitt 12\n20146 Hamburg",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Firmenfitness-Programm.",
  },
  {
    id: "crossfit",
    name: "CrossFit Box (Franchise)",
    category: "fitness",
    address: "(Adresse Ihrer lokalen CrossFit Box eintragen)",
    kuendigungsfrist: "Unterschiedlich je nach Box",
    mindestlaufzeit: "Unterschiedlich",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Kündigung direkt bei der jeweiligen Box.",
  },
  {
    id: "easyfitness",
    name: "easyFitness",
    category: "fitness",
    address: "(Adresse Ihres lokalen Studios eintragen)",
    kuendigungsfrist: "1-3 Monate zum Vertragsende",
    mindestlaufzeit: "12-24 Monate",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Discounter-Fitnesskette.",
  },

  // ========== STREAMING & MEDIEN ==========
  {
    id: "netflix",
    name: "Netflix",
    category: "streaming",
    address: "Netflix International B.V.\nKarperstraat 8-10\n1075 KZ Amsterdam, Niederlande",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung direkt über die Netflix-Kontoeinstellungen.",
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "streaming",
    address: "Spotify AB\nRegeringsgatan 19\n111 53 Stockholm, Schweden",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über spotify.com/account.",
  },
  {
    id: "amazon-prime",
    name: "Amazon Prime / Prime Video",
    category: "streaming",
    address: "Amazon Europe Core S.à r.l.\n38 avenue John F. Kennedy\nL-1855 Luxemburg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über Amazon-Kontoeinstellungen. Anteilige Erstattung möglich.",
  },
  {
    id: "dazn",
    name: "DAZN",
    category: "streaming",
    address: "DAZN Limited\n12 Hammersmith Grove\nLondon W6 7AP, UK",
    kuendigungsfrist: "30 Tage",
    mindestlaufzeit: "Abhängig vom gewählten Abo",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über die DAZN-App oder Webseite. Auf 30-Tage-Frist achten.",
  },
  {
    id: "sky",
    name: "Sky / WOW",
    category: "streaming",
    address: "Sky Deutschland Fernsehen GmbH & Co. KG\nMedienallee 26\n85774 Unterföhring",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "Abhängig vom Abo",
    kuendigungsart: ["Schriftlich", "Online", "Telefon"],
    hinweise: "WOW (ehem. Sky Ticket) ist online kündbar. Reguläres Sky-Abo kann per Brief/Chat gekündigt werden.",
  },
  {
    id: "disney-plus",
    name: "Disney+",
    category: "streaming",
    address: "The Walt Disney Company (Benelux) B.V.\nDe Passage 144\n1101 AX Amsterdam, Niederlande",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über die Disney+ Kontoeinstellungen.",
  },
  {
    id: "apple-tv-plus",
    name: "Apple TV+",
    category: "streaming",
    address: "Apple Distribution International Ltd.\nHollyhill Industrial Estate\nCork, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über Apple-ID Einstellungen.",
  },
  {
    id: "rtlplus",
    name: "RTL+",
    category: "streaming",
    address: "RTL interactive GmbH\nPicassoplatz 1\n50679 Köln",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Vormals TVNow. Kündigung über rtlplus.de Kontoeinstellungen.",
  },
  {
    id: "joyn",
    name: "Joyn PLUS+",
    category: "streaming",
    address: "Joyn GmbH\nMedienallee 4\n85774 Unterföhring",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über das Joyn-Konto.",
  },
  {
    id: "audible",
    name: "Audible",
    category: "streaming",
    address: "Audible GmbH\nAuer-Welsbach-Straße 47\n81379 München",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Abo kann pausiert werden. Guthaben bleibt nach Kündigung NICHT erhalten!",
  },
  {
    id: "deezer",
    name: "Deezer",
    category: "streaming",
    address: "Deezer SA\n24 rue de Calais\n75009 Paris, Frankreich",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über deezer.com Kontoeinstellungen.",
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    category: "streaming",
    address: "Google Ireland Ltd.\nGordon House, Barrow Street\nDublin 4, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über Google-Kontoeinstellungen.",
  },
  {
    id: "paramount-plus",
    name: "Paramount+",
    category: "streaming",
    address: "Paramount Global\nc/o Paramount Germany GmbH\nKemperplatz 1\n10785 Berlin",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über Kontoeinstellungen auf paramountplus.com.",
  },
  {
    id: "crunchyroll",
    name: "Crunchyroll",
    category: "streaming",
    address: "Crunchyroll LLC\n835 Market St\nSan Francisco, CA 94103, USA",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo) / 12 Monate",
    kuendigungsart: ["Online"],
    hinweise: "Anime-Streaming Service. Kündigung über Kontoeinstellungen.",
  },
  {
    id: "magentasport",
    name: "MagentaSport",
    category: "streaming",
    address: "Telekom Deutschland GmbH\nLandgrabenweg 151\n53227 Bonn",
    kuendigungsfrist: "Monatlich kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Sport-Streaming der Telekom.",
  },
  {
    id: "mubi",
    name: "MUBI",
    category: "streaming",
    address: "MUBI Inc.\n200 Aldersgate\nLondon EC1A 4HD, UK",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Arthouse-Cinema Streaming.",
  },
  {
    id: "apple-music",
    name: "Apple Music",
    category: "streaming",
    address: "Apple Distribution International Ltd.\nHollyhill Industrial Estate\nCork, Irland",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über iTunes/Apple-ID-Einstellungen.",
  },
  {
    id: "blinkist",
    name: "Blinkist",
    category: "streaming",
    address: "Blinks Labs GmbH\nSonnenallee 223\n12059 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Buchzusammenfassungen-App.",
  },

  // ========== BANK & FINANZEN ==========
  {
    id: "sparkasse",
    name: "Sparkasse (Allgemein)",
    category: "bank",
    address: "(Adresse Ihrer lokalen Sparkasse eintragen)",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Girokonto jederzeit kündbar. Kündigung an die jeweilige LOKALE Filiale senden.",
  },
  {
    id: "dkb",
    name: "DKB (Deutsche Kreditbank)",
    category: "bank",
    address: "Deutsche Kreditbank AG\nTaubenstraße 7-9\n10117 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Konto vorher auf 0 bringen. Neue Bankverbindung für Restguthaben angeben.",
  },
  {
    id: "ing",
    name: "ING",
    category: "bank",
    address: "ING-DiBa AG\n60628 Frankfurt am Main",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kündigung am einfachsten über das Internetbanking (Service > Konto & Karten).",
  },
  {
    id: "commerzbank",
    name: "Commerzbank",
    category: "bank",
    address: "Commerzbank AG\n60261 Frankfurt am Main",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kündigungsschreiben am besten per Einschreiben senden.",
  },
  {
    id: "n26",
    name: "N26",
    category: "bank",
    address: "N26 Bank GmbH\nVoltairestraße 8\n10179 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine (außer bei Smart/Metal)",
    kuendigungsart: ["Online", "App", "E-Mail"],
    hinweise: "Kündigung direkt über die N26-App unter Konto-Einstellungen.",
  },
  {
    id: "deutsche-bank",
    name: "Deutsche Bank",
    category: "bank",
    address: "Deutsche Bank AG\n60262 Frankfurt am Main",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Kündigung schriftlich an die kontoführende Filiale.",
  },
  {
    id: "postbank",
    name: "Postbank",
    category: "bank",
    address: "Deutsche Bank AG (Postbank)\nPostfach 40 00\n53105 Bonn",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Seit 2023 vollständig Teil der Deutschen Bank.",
  },
  {
    id: "comdirect",
    name: "comdirect",
    category: "bank",
    address: "comdirect (Commerzbank AG)\nPascalkehre 15\n25451 Quickborn",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehört zur Commerzbank. Online-Kündigung möglich.",
  },
  {
    id: "targobank",
    name: "TARGOBANK",
    category: "bank",
    address: "TARGOBANK AG\nKasernenstraße 10\n40213 Düsseldorf",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Girokonto jederzeit kündbar. Kreditverträge haben separate Fristen.",
  },
  {
    id: "volksbank",
    name: "Volksbank / Raiffeisenbank",
    category: "bank",
    address: "(Adresse Ihrer lokalen Volksbank eintragen)",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Genossenschaftsbank. Kündigung an die lokale Filiale richten.",
  },
  {
    id: "consorsbank",
    name: "Consorsbank",
    category: "bank",
    address: "BNP Paribas S.A. Niederlassung Deutschland\nBahnhofstr. 55\n90402 Nürnberg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online- oder schriftliche Kündigung.",
  },
  {
    id: "santander",
    name: "Santander Consumer Bank",
    category: "bank",
    address: "Santander Consumer Bank AG\nSantander-Platz 1\n41061 Mönchengladbach",
    kuendigungsfrist: "Jederzeit (Konto) / Vertragsabhängig (Kredit)",
    mindestlaufzeit: "Keine (Konto)",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kreditverträge: Sondertilgungsrecht/Ablösung prüfen.",
  },
  {
    id: "scalable-capital",
    name: "Scalable Capital",
    category: "bank",
    address: "Scalable Capital GmbH\nSeitzstraße 8e\n80538 München",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "App"],
    hinweise: "Depot-Kündigung über die App. Alle Wertpapiere vorher übertragen oder verkaufen.",
  },
  {
    id: "trade-republic",
    name: "Trade Republic",
    category: "bank",
    address: "Trade Republic Bank GmbH\nBrunnenstraße 19-21\n10119 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "App"],
    hinweise: "Depot-Kündigung über die App. Guthaben vorher überweisen.",
  },
  {
    id: "wuestenrot",
    name: "Wüstenrot Bausparkasse",
    category: "bank",
    address: "Wüstenrot Bausparkasse AG\nWüstenrotstr. 1\n71630 Ludwigsburg",
    kuendigungsfrist: "3 Monate zum Quartalsende",
    mindestlaufzeit: "Laut Bausparvertrag",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Bausparvertrag kann nach Zuteilungsreife jederzeit gekündigt werden.",
  },
  {
    id: "netbank",
    name: "netbank",
    category: "bank",
    address: "Augsburger Aktienbank AG\nHalderstr. 5\n86150 Augsburg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online-Bank, Teil der Augsburger Aktienbank.",
  },
  {
    id: "flatex",
    name: "flatex",
    category: "bank",
    address: "flatexDEGIRO Bank AG\nRotfeder-Ring 7\n60327 Frankfurt am Main",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Online-Broker. Positionen vorab verkaufen oder übertragen.",
  },
  {
    id: "sparkasse-koeln",
    name: "Sparkasse KölnBonn",
    category: "bank",
    address: "Sparkasse KölnBonn\nHahnenstraße 57\n50667 Köln",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Regionale Sparkasse.",
  },
  {
    id: "berliner-sparkasse",
    name: "Berliner Sparkasse",
    category: "bank",
    address: "Berliner Sparkasse\nAlexanderplatz 2\n10178 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Größte Sparkasse Deutschlands.",
  },
  {
    id: "haspa",
    name: "Hamburger Sparkasse (Haspa)",
    category: "bank",
    address: "Haspa\nAdolphsplatz 1\n20457 Hamburg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Persönlich"],
    hinweise: "Regionale Sparkasse Hamburg.",
  },
  {
    id: "revolut",
    name: "Revolut",
    category: "bank",
    address: "Revolut Bank UAB\nKonstitucijos ave. 21B\n08130 Vilnius, Litauen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["App"],
    hinweise: "Kündigung ausschließlich über die App möglich.",
  },
  {
    id: "wise",
    name: "Wise (TransferWise)",
    category: "bank",
    address: "Wise Europe SA\nRue du Trône 100\n1050 Brüssel, Belgien",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "App"],
    hinweise: "Multi-Währungs-Konto.",
  },
  {
    id: "bunq",
    name: "bunq",
    category: "bank",
    address: "bunq B.V.\nNaritaweg 165\n1043 BW Amsterdam, Niederlande",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["App"],
    hinweise: "Kündigung in der App unter Profile -> Settings -> Close Account.",
  },

  // ========== VERLAG & ZEITSCHRIFTEN ==========
  {
    id: "spiegel",
    name: "Der Spiegel / SPIEGEL+",
    category: "verlag",
    address: "SPIEGEL-Verlag Rudolf Augstein GmbH & Co. KG\nAbo-Service\nEricusspitze 1\n20457 Hamburg",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhängig vom Abo",
    kuendigungsart: ["Schriftlich", "Online", "E-Mail"],
    hinweise: "Digital-Abo jederzeit online kündbar. Print: Kundennummer angeben.",
  },
  {
    id: "zeit",
    name: "Die Zeit",
    category: "verlag",
    address: "Zeitverlag Gerd Bucerius GmbH & Co. KG\nAbo-Service\n20080 Hamburg",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhängig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "E-Mail: abo@zeit.de",
  },
  {
    id: "sueddeutsche",
    name: "Süddeutsche Zeitung",
    category: "verlag",
    address: "Süddeutsche Zeitung GmbH\nAbo-Service\nHultschiner Str. 8\n81677 München",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Abhängig vom Abo",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "SZ Plus kann im Account gekündigt werden.",
  },
  {
    id: "bild",
    name: "BILD / BILDplus",
    category: "verlag",
    address: "Axel Springer SE\nAbo-Service\nAxel-Springer-Str. 65\n10888 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende (Digital)",
    mindestlaufzeit: "Keine (Digital-Abo)",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Aboverwaltung über mypass.de.",
  },
  {
    id: "faz",
    name: "Frankfurter Allgemeine Zeitung (FAZ)",
    category: "verlag",
    address: "Frankfurter Allgemeine Zeitung GmbH\nAbo-Service\nHellerhofstr. 2-4\n60327 Frankfurt am Main",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Abhängig vom Abo",
    kuendigungsart: ["Schriftlich", "Online", "E-Mail"],
    hinweise: "E-Mail: abo-service@faz.de",
  },
  {
    id: "welt",
    name: "Die Welt / WELTplus",
    category: "verlag",
    address: "Axel Springer SE\nAbo-Service\n10888 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende (Digital)",
    mindestlaufzeit: "Keine (Digital-Abo)",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Aboverwaltung über mypass.de.",
  },
  {
    id: "focus",
    name: "FOCUS",
    category: "verlag",
    address: "FOCUS Magazin Verlag GmbH\nArabellastraße 23\n81925 München",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhängig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Kundennummer im Schreiben angeben.",
  },
  {
    id: "stern",
    name: "stern",
    category: "verlag",
    address: "Gruner + Jahr GmbH\nAbo-Service\nAm Baumwall 11\n20459 Hamburg",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhängig vom Abo",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehört zur RTL-Gruppe.",
  },
  {
    id: "handelsblatt",
    name: "Handelsblatt",
    category: "verlag",
    address: "Handelsblatt Media Group GmbH & Co. KG\nKasernenstr. 67\n40213 Düsseldorf",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Abhängig vom Abo",
    kuendigungsart: ["Schriftlich", "Online", "E-Mail"],
    hinweise: "E-Mail: leserservice@handelsblatt.com",
  },
  {
    id: "berliner-zeitung",
    name: "Berliner Zeitung",
    category: "verlag",
    address: "Berliner Verlag GmbH\nAlte Jakobstraße 105\n10969 Berlin",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Je nach Abo-Modell",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Digital-Abo kann online gekündigt werden.",
  },
  {
    id: "rheinische-post",
    name: "Rheinische Post",
    category: "verlag",
    address: "Rheinische Post Mediengruppe\nZülpicher Str. 10\n40196 Düsseldorf",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Je nach Abo-Modell",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Kündigungsbestätigung anfordern.",
  },
  {
    id: "stuttgarter-zeitung",
    name: "Stuttgarter Zeitung",
    category: "verlag",
    address: "Stuttgarter Zeitung Verlagsgesellschaft mbH\nPlieninger Str. 150\n70567 Stuttgart",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Je nach Abo-Modell",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Auch digital-only Abonnements mit gleicher Frist.",
  },
  {
    id: "bunte",
    name: "BUNTE",
    category: "verlag",
    address: "Bunte Entertainment Verlag GmbH\nArabellastr. 23\n81925 München",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "People-Magazin.",
  },
  {
    id: "geo",
    name: "GEO (Abo)",
    category: "verlag",
    address: "Gruner + Jahr GmbH\nAm Baumwall 11\n20459 Hamburg",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Wissenschaftsmagazin.",
  },
  {
    id: "auto-motor-sport",
    name: "auto motor und sport",
    category: "verlag",
    address: "Motor Presse Stuttgart GmbH & Co. KG\nLeuschnerstraße 1\n70174 Stuttgart",
    kuendigungsfrist: "6 Wochen zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Automobilmagazin.",
  },

  // ========== MITGLIEDSCHAFT & VEREIN ==========
  {
    id: "adac",
    name: "ADAC",
    category: "mitgliedschaft",
    address: "ADAC e.V.\nHansastraße 19\n80686 München",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kündigung kann bequem über das Webportal ('Mein ADAC') durchgeführt werden.",
  },
  {
    id: "gewerkschaft-verdi",
    name: "ver.di Gewerkschaft",
    category: "mitgliedschaft",
    address: "ver.di Bundesverwaltung\nPaula-Thiede-Ufer 10\n10179 Berlin",
    kuendigungsfrist: "3 Monate zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Austritt in der Regel bei der lokalen/zuständigen Bezirksverwaltung einreichen!",
  },
  {
    id: "bahncard",
    name: "BahnCard (25, 50, 100)",
    category: "mitgliedschaft",
    address: "BahnCard Service\n60643 Frankfurt am Main",
    kuendigungsfrist: "6 Wochen vor Ablauf",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Automatische Verlängerung verhindern! Sofort nach Kauf im Bahn.de Account kündigen.",
  },
  {
    id: "ig-metall",
    name: "IG Metall",
    category: "mitgliedschaft",
    address: "IG Metall Vorstand\nWilhelm-Leuschner-Straße 79\n60329 Frankfurt am Main",
    kuendigungsfrist: "3 Monate zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Austritt schriftlich an die lokale Verwaltungsstelle senden.",
  },
  {
    id: "gez-rundfunkbeitrag",
    name: "Rundfunkbeitrag (GEZ)",
    category: "mitgliedschaft",
    address: "ARD ZDF Deutschlandradio Beitragsservice\n50656 Köln",
    kuendigungsfrist: "Abmeldung bei Umzug/Zusammenzug",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Abmeldung nur bei Abmeldung der Wohnung, Umzug ins Ausland oder Zusammenzug möglich.",
  },
  {
    id: "amazon-prime-member",
    name: "Amazon Prime (Mitgliedschaft)",
    category: "mitgliedschaft",
    address: "Amazon Europe Core S.à r.l.\n38 avenue John F. Kennedy\nL-1855 Luxemburg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über Amazon-Konto. Anteilige Erstattung bei Jahresabo möglich.",
  },
  {
    id: "automobilclub-ace",
    name: "ACE Auto Club Europa",
    category: "mitgliedschaft",
    address: "ACE Auto Club Europa e.V.\nSchmidener Straße 227\n70374 Stuttgart",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Alternative zum ADAC.",
  },
  {
    id: "avd",
    name: "AvD (Automobilclub von Deutschland)",
    category: "mitgliedschaft",
    address: "Automobilclub von Deutschland e.V.\nLyoner Straße 16\n60528 Frankfurt am Main",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Traditionsreicher Automobilclub. Einschreiben empfohlen.",
  },
  {
    id: "adfc",
    name: "ADFC (Fahrradclub)",
    category: "mitgliedschaft",
    address: "Allgemeiner Deutscher Fahrrad-Club e.V.\nMohrenstr. 69\n10117 Berlin",
    kuendigungsfrist: "6 Wochen zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Mitgliedschaft im Fahrrad-Club.",
  },
  {
    id: "nabu",
    name: "NABU",
    category: "mitgliedschaft",
    address: "NABU-Bundesverband\nCharitéstraße 3\n10117 Berlin",
    kuendigungsfrist: "Jederzeit zum Jahresende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Naturschutzverband.",
  },
  {
    id: "amnesty",
    name: "Amnesty International",
    category: "mitgliedschaft",
    address: "Amnesty International Deutschland e.V.\nZinnowitzer Str. 8\n10115 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Menschenrechtsorganisation.",
  },
  {
    id: "vdk",
    name: "Sozialverband VdK",
    category: "mitgliedschaft",
    address: "Sozialverband VdK Deutschland e.V.\nLinienstraße 131\n10115 Berlin",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sozialverband. Lokale Adresse des Landesverbandes prüfen.",
  },
  {
    id: "bund",
    name: "BUND",
    category: "mitgliedschaft",
    address: "Bund für Umwelt und Naturschutz Deutschland e.V.\nKaiserstr. 93\n53113 Bonn",
    kuendigungsfrist: "Jederzeit zum Jahresende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Umweltschutzorganisation.",
  },
  {
    id: "greenpeace",
    name: "Greenpeace (Fördermitgliedschaft)",
    category: "mitgliedschaft",
    address: "Greenpeace e.V.\nHongkongstraße 10\n20457 Hamburg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Umweltorganisation.",
  },
  {
    id: "wwf",
    name: "WWF (World Wide Fund For Nature)",
    category: "mitgliedschaft",
    address: "WWF Deutschland\nReinhardtstraße 18\n10117 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Naturschutzorganisation.",
  },

  // ========== JOB & KARRIERE ==========
  {
    id: "stepstone",
    name: "StepStone",
    category: "arbeit",
    address: "StepStone Deutschland GmbH\nVölklinger Straße 1\n40219 Düsseldorf",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Premium-Stellenanzeigen und Abos online kündbar unter stepstone.de/account.",
  },
  {
    id: "indeed",
    name: "Indeed",
    category: "arbeit",
    address: "Indeed Ireland Operations Ltd.\n124 St. Stephen's Green\nDublin 2, Irland",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über Konto-Einstellungen auf indeed.com.",
  },
  {
    id: "linkedin-jobs",
    name: "LinkedIn Jobs / Recruiter",
    category: "arbeit",
    address: "LinkedIn Ireland Unlimited Company\nWilton Plaza\nDublin 2, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Job-Postings und Recruiter-Pakete über linkedin.com Kontoeinstellungen kündbar.",
  },
  {
    id: "xing-jobs",
    name: "XING Jobs / TalentManager",
    category: "arbeit",
    address: "New Work SE\nAm Strandkai 1\n20457 Hamburg",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über xing.com Kontoeinstellungen.",
  },
  {
    id: "monster",
    name: "Monster",
    category: "arbeit",
    address: "Monster Worldwide Deutschland GmbH\nNymphenburger Str. 3\n80335 München",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto und Abonnements über monster.de kündbar.",
  },
  {
    id: "arbeitsagentur",
    name: "Bundesagentur für Arbeit (Jobprofil)",
    category: "arbeit",
    address: "Bundesagentur für Arbeit\nRegensburger Straße 104\n90478 Nürnberg",
    kuendigungsfrist: "Keine",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kostenloses Jobportal. Bewerberprofil jederzeit löschbar unter arbeitsagentur.de.",
  },
  {
    id: "hokify",
    name: "hokify",
    category: "arbeit",
    address: "hokify GmbH\nMariahilfer Straße 50\n1070 Wien, Österreich",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Mobile Job-Plattform. Konto über App-Einstellungen löschbar.",
  },
  {
    id: "jobware",
    name: "Jobware",
    category: "arbeit",
    address: "Jobware Online-Service GmbH\nTechnologiepark 15\n33100 Paderborn",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Stellenanzeigen-Portal.",
  },

  // ========== SONSTIGES ==========
  {
    id: "check24",
    name: "CHECK24",
    category: "sonstiges",
    address: "CHECK24 Vergleichsportal GmbH\nErika-Mann-Str. 62-66\n80636 München",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto jederzeit löschbar. E-Mail: kundenservice@check24.de",
  },
  {
    id: "parship",
    name: "Parship",
    category: "sonstiges",
    address: "PE Digital GmbH\nSpeersort 10\n20095 Hamburg",
    kuendigungsfrist: "12 Wochen zum Vertragsende",
    mindestlaufzeit: "6-24 Monate",
    kuendigungsart: ["Schriftlich", "Fax"],
    hinweise: "Widerruf innerhalb von 14 Tagen. Danach: 12 Wochen Frist. Einschreiben empfohlen!",
  },
  {
    id: "elitepartner",
    name: "ElitePartner",
    category: "sonstiges",
    address: "PE Digital GmbH\nSpeersort 10\n20095 Hamburg",
    kuendigungsfrist: "12 Wochen zum Vertragsende",
    mindestlaufzeit: "6-24 Monate",
    kuendigungsart: ["Schriftlich", "Fax"],
    hinweise: "Gleiche Firma und Frist wie Parship.",
  },
  {
    id: "verivox",
    name: "Verivox",
    category: "sonstiges",
    address: "Verivox GmbH\nAm Taubenfeld 10\n69123 Heidelberg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Vergleichsportal. Konto jederzeit löschbar.",
  },
  {
    id: "schufa",
    name: "SCHUFA (meineSCHUFA)",
    category: "sonstiges",
    address: "SCHUFA Holding AG\nKormoranweg 5\n65201 Wiesbaden",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "meineSCHUFA-Paket online kündbar. Vorsicht vor Abo-Verlängerung.",
  },
  {
    id: "payback",
    name: "PAYBACK",
    category: "sonstiges",
    address: "PAYBACK GmbH\nTheresienhöhe 12\n80339 München",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Punkte vor Kündigung einlösen! E-Mail: service@payback.de",
  },
  {
    id: "deutschlandcard",
    name: "DeutschlandCard",
    category: "sonstiges",
    address: "DeutschlandCard GmbH\nNeumarkter Straße 22\n81673 München",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Punkte vor Kündigung einlösen.",
  },
  {
    id: "immoscout24",
    name: "ImmobilienScout24 (MieterPlus)",
    category: "sonstiges",
    address: "Immobilien Scout GmbH\nInvalidenstraße 65\n10557 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende (Premium)",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "MieterPlus/Premium kündbar in den Kontoeinstellungen.",
  },
  {
    id: "ebay-kleinanzeigen",
    name: "Kleinanzeigen (ehem. eBay)",
    category: "sonstiges",
    address: "Kleinanzeigen GmbH\nAlbert-Einstein-Ring 26\n14532 Kleinmachnow",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Konto online löschbar.",
  },
  {
    id: "lieferando",
    name: "Lieferando",
    category: "sonstiges",
    address: "Takeaway.com Group B.V.\nOosterdoksstraat 80\n1011 DK Amsterdam, Niederlande",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto löschbar über Kontoeinstellungen.",
  },
  {
    id: "hellofresh",
    name: "HelloFresh",
    category: "sonstiges",
    address: "HelloFresh SE\nPrinzenstraße 89\n10969 Berlin",
    kuendigungsfrist: "Jederzeit (vor Bestellfrist der nächsten Woche)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Abo pausieren oder kündigen über die App/Webseite.",
  },
  {
    id: "marley-spoon",
    name: "Marley Spoon",
    category: "sonstiges",
    address: "Marley Spoon GmbH\nPaul-Lincke-Ufer 39/40\n10999 Berlin",
    kuendigungsfrist: "Jederzeit (vor Bestellfrist)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kochbox-Abo jederzeit pausierbar/kündbar.",
  },
  {
    id: "mydays",
    name: "mydays",
    category: "sonstiges",
    address: "mydays GmbH\nAm Münchner Tor 6\n85609 Aschheim",
    kuendigungsfrist: "Jederzeit (Gutscheine verfallen nach Frist)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["E-Mail"],
    hinweise: "Konto löschbar per E-Mail an den Kundenservice.",
  },
  {
    id: "tinder",
    name: "Tinder",
    category: "sonstiges",
    address: "Match Group, LLC\n8750 N. Central Expressway\nDallas, TX 75231, USA",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "App Store"],
    hinweise: "Kündigung über App Store / Google Play oder tinder.com.",
  },
  {
    id: "bumble",
    name: "Bumble",
    category: "sonstiges",
    address: "Bumble Inc.\nAustin, TX, USA",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "App Store"],
    hinweise: "Kündigung zwingend über App Store / Google Play durchführen.",
  },
  {
    id: "mcdonalds-app",
    name: "McDonald's App (Rewards)",
    category: "sonstiges",
    address: "McDonald's Deutschland LLC\nDrygalski-Allee 51\n81477 München",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Konto löschbar über App-Einstellungen.",
  },
  {
    id: "flixbus",
    name: "FlixBus / Flixtrain",
    category: "sonstiges",
    address: "FlixMobility GmbH\nFriedenheimer Brücke 16\n80639 München",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto löschbar. Einzelbuchungen stornierbar je nach Tarif.",
  },
  {
    id: "sixt",
    name: "SIXT (Abo/Flatrate)",
    category: "sonstiges",
    address: "Sixt SE\nZugspitzstraße 1\n82049 Pullach",
    kuendigungsfrist: "Vertragsabhängig",
    mindestlaufzeit: "Abhängig vom Abo-Modell",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Auto-Abo Kündigungsfristen im Vertrag prüfen.",
  },
  {
    id: "miles",
    name: "MILES Carsharing",
    category: "sonstiges",
    address: "MILES Mobility GmbH\nLeibnizstraße 49\n10629 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto löschbar über die App.",
  },
  {
    id: "share-now",
    name: "SHARE NOW",
    category: "sonstiges",
    address: "SHARE NOW GmbH\nBrunnenstraße 19-21\n10119 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Konto kündbar über die App.",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    category: "sonstiges",
    address: "Dropbox International Unlimited Company\nDublin, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über dropbox.com Kontoeinstellungen.",
  },
  {
    id: "icloud",
    name: "iCloud+ (Apple)",
    category: "sonstiges",
    address: "Apple Distribution International Ltd.\nCork, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über Apple-ID Einstellungen (iPhone, iPad, Mac).",
  },
  {
    id: "microsoft365",
    name: "Microsoft 365",
    category: "sonstiges",
    address: "Microsoft Ireland Operations Ltd.\nDublin, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über account.microsoft.com.",
  },
  {
    id: "google-one",
    name: "Google One",
    category: "sonstiges",
    address: "Google Ireland Ltd.\nDublin 4, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über Google-Kontoeinstellungen.",
  },
  {
    id: "adobe-cc",
    name: "Adobe Creative Cloud",
    category: "sonstiges",
    address: "Adobe Systems Software Ireland Ltd.\nDublin, Irland",
    kuendigungsfrist: "14 Tage Widerruf / Vorzeitige Kündigung mit Gebühr",
    mindestlaufzeit: "12 Monate (Jahresabo)",
    kuendigungsart: ["Online"],
    hinweise: "Vorzeitige Kündigung des Jahresabos: 50% der Restlaufzeit als Gebühr.",
  },
  {
    id: "linkedin-premium",
    name: "LinkedIn Premium",
    category: "sonstiges",
    address: "LinkedIn Ireland Unlimited Company\nDublin, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über linkedin.com Kontoeinstellungen.",
  },
  {
    id: "xing-premium",
    name: "XING Premium",
    category: "sonstiges",
    address: "New Work SE\nAm Strandkai 1\n20457 Hamburg",
    kuendigungsfrist: "3 Wochen zum Vertragsende",
    mindestlaufzeit: "Keine (Monatsabo) / 12 Monate",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über xing.com Kontoeinstellungen.",
  },
  {
    id: "chatgpt-plus",
    name: "ChatGPT Plus (OpenAI)",
    category: "sonstiges",
    address: "OpenAI, L.L.C.\n3180 18th Street\nSan Francisco, CA 94110, USA",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kündigung über chat.openai.com Kontoeinstellungen.",
  },
  {
    id: "tier-scooter",
    name: "TIER E-Scooter",
    category: "sonstiges",
    address: "TIER Mobility SE\nc/o Dott, Eichhornstraße 3\n10785 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Account-Löschung über die App oder per E-Mail.",
  },
  {
    id: "voi-scooter",
    name: "Voi E-Scooter",
    category: "sonstiges",
    address: "Voi Technology AB\nStockholm, Schweden",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Account-Löschung über die App oder per E-Mail an support@voiapp.io.",
  },
  {
    id: "jochen-schweizer",
    name: "Jochen Schweizer",
    category: "sonstiges",
    address: "Jochen Schweizer mydays Group GmbH\nRosenheimer Str. 145e\n81671 München",
    kuendigungsfrist: "Keine - Gutscheine",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["E-Mail"],
    hinweise: "Erlebnisgutscheine. Verfallen nach gesetzlicher Frist.",
  },
  {
    id: "fleurop",
    name: "Fleurop",
    category: "sonstiges",
    address: "Fleurop AG\nLindenstraße 3-4\n12207 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["E-Mail"],
    hinweise: "Blumenversand. Account löschbar.",
  },
  {
    id: "weltbild",
    name: "Weltbild",
    category: "sonstiges",
    address: "Weltbild GmbH & Co. KG\nSteinerne Furt 67\n86167 Augsburg",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["E-Mail", "Schriftlich"],
    hinweise: "Online-Shop für Bücher und Medien. Kundenkonto löschen.",
  },
  {
    id: "tchibo",
    name: "Tchibo (Kundenkonto)",
    category: "sonstiges",
    address: "Tchibo GmbH\nÜberseering 18\n22297 Hamburg",
    kuendigungsfrist: "Jederzeit kündbar",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "Schriftlich"],
    hinweise: "Kundenkonto (TchiboCard) kündigen.",
  }
];