export type CompanyCategory =
  | "telekommunikation"
  | "versicherung"
  | "energie"
  | "fitness"
  | "streaming"
  | "bank"
  | "internet"
  | "mobilfunk"
  | "verlag"
  | "mitgliedschaft"
  | "sonstiges"

export interface Company {
  id: string
  name: string
  category: CompanyCategory
  address: string
  kuendigungsfrist: string
  mindestlaufzeit: string
  kuendigungsart: string[]
  hinweise: string
}

export const CATEGORY_LABELS: Record<CompanyCategory, string> = {
  telekommunikation: "Telekommunikation",
  versicherung: "Versicherung",
  energie: "Energie",
  fitness: "Fitness & Sport",
  streaming: "Streaming & Medien",
  bank: "Bank & Finanzen",
  internet: "Internet & DSL",
  mobilfunk: "Mobilfunk",
  verlag: "Verlag & Zeitschriften",
  mitgliedschaft: "Mitgliedschaft & Verein",
  sonstiges: "Sonstiges",
}

export const companies: Company[] = [
  // ========== TELEKOMMUNIKATION ==========
  {
    id: "telekom",
    name: "Deutsche Telekom",
    category: "telekommunikation",
    address: "Telekom Deutschland GmbH\nKundenservice\n53171 Bonn",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online-Kuendigung ueber das Kundencenter moeglich.",
  },
  {
    id: "vodafone",
    name: "Vodafone",
    category: "telekommunikation",
    address: "Vodafone GmbH\nKundenbetreuung\n40549 Duesseldorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Fax", "Online"],
    hinweise: "Fax: 0211 533 1612. Online-Kuendigung ueber MeinVodafone.",
  },
  {
    id: "o2",
    name: "O2 / Telefonica",
    category: "telekommunikation",
    address: "Telefonica Germany GmbH & Co. OHG\nKundenbetreuung\n90345 Nuernberg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kuendigung per Brief oder ueber Mein O2 online.",
  },
  {
    id: "1und1",
    name: "1&1",
    category: "telekommunikation",
    address: "1&1 Telecom GmbH\nElgendorfer Strasse 57\n56410 Montabaur",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung am besten per Einschreiben senden.",
  },
  {
    id: "freenet",
    name: "freenet",
    category: "telekommunikation",
    address: "freenet AG\nHollerstrasse 126\n24782 Buedelsdorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Verschiedene Marken (mobilcom-debitel, klarmobil). Vertrag pruefen!",
  },
  {
    id: "mobilcom-debitel",
    name: "mobilcom-debitel",
    category: "telekommunikation",
    address: "freenet AG\nHollerstrasse 126\n24782 Buedelsdorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehoert zur freenet-Gruppe. Kuendigung auch online im Kundencenter.",
  },

  // ========== MOBILFUNK ==========
  {
    id: "congstar",
    name: "congstar",
    category: "mobilfunk",
    address: "congstar GmbH\nKundenservice\n50969 Koeln",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate (Allnet Flat), keine (Prepaid)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Prepaid-Tarife sind jederzeit kuendbar.",
  },
  {
    id: "aldi-talk",
    name: "ALDI TALK",
    category: "mobilfunk",
    address: "Medion AG\nAm Zehnthof 77\n45307 Essen",
    kuendigungsfrist: "Keine (Prepaid)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Prepaid-Karte jederzeit kuendbar. E-Mail: kundenservice@alditalk.de",
  },
  {
    id: "lidl-connect",
    name: "Lidl Connect",
    category: "mobilfunk",
    address: "Lidl Connect Kundenbetreuung\nPostfach 10 01 53\n40001 Duesseldorf",
    kuendigungsfrist: "Keine (Prepaid)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Prepaid-Karte. Kuendigung jederzeit moeglich.",
  },
  {
    id: "klarmobil",
    name: "klarmobil",
    category: "mobilfunk",
    address: "klarmobil GmbH\nHollerstrasse 126\n24782 Buedelsdorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate (Laufzeitvertrag)",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Gehoert zur freenet-Gruppe.",
  },
  {
    id: "blau",
    name: "Blau",
    category: "mobilfunk",
    address: "Blau Service GmbH\n90345 Nuernberg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate / monatlich kuendbar",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehoert zum O2/Telefonica-Netz.",
  },
  {
    id: "simyo",
    name: "simyo",
    category: "mobilfunk",
    address: "Telefonica Germany GmbH & Co. OHG\n90345 Nuernberg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Marke von Telefonica/O2.",
  },
  {
    id: "otelo",
    name: "otelo",
    category: "mobilfunk",
    address: "Vodafone GmbH\n40549 Duesseldorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Discount-Marke von Vodafone.",
  },
  {
    id: "winSIM",
    name: "winSIM",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Roentgen-Strasse 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate / monatlich kuendbar",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Gehoert zur Drillisch/1&1-Gruppe.",
  },
  {
    id: "premiumsim",
    name: "PremiumSIM",
    category: "mobilfunk",
    address: "Drillisch Online GmbH\nWilhelm-Roentgen-Strasse 1-5\n63477 Maintal",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate / monatlich kuendbar",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Drillisch-Marke. Monatlich kuendbare Tarife verfuegbar.",
  },
  {
    id: "fraenk",
    name: "fraenk",
    category: "mobilfunk",
    address: "fraenk (Telekom)\n53171 Bonn",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Monatlich kuendbar ueber die fraenk-App.",
  },

  // ========== VERSICHERUNG ==========
  {
    id: "allianz",
    name: "Allianz Versicherung",
    category: "versicherung",
    address: "Allianz Versicherungs-AG\n10900 Berlin",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkuendigungsrecht bei Beitragserhohung. Vertragsnummer angeben!",
  },
  {
    id: "huk-coburg",
    name: "HUK-COBURG",
    category: "versicherung",
    address: "HUK-COBURG\nBahnhofsplatz\n96450 Coburg",
    kuendigungsfrist: "1 Monat zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kfz-Versicherung: Stichtag ist der 30. November.",
  },
  {
    id: "ergo",
    name: "ERGO Versicherung",
    category: "versicherung",
    address: "ERGO Versicherung AG\n40198 Duesseldorf",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer und Versicherungsscheinnummer im Schreiben angeben.",
  },
  {
    id: "axa",
    name: "AXA Versicherung",
    category: "versicherung",
    address: "AXA Konzern AG\n51171 Koeln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkuendigungsrecht bei Beitragsanpassung innerhalb eines Monats.",
  },
  {
    id: "debeka",
    name: "Debeka",
    category: "versicherung",
    address: "Debeka\nFerdinand-Sauerbruch-Strasse 18\n56073 Koblenz",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Krankenversicherung: Besondere Regelungen beachten!",
  },
  {
    id: "generali",
    name: "Generali Versicherung",
    category: "versicherung",
    address: "Generali Deutschland AG\nAdenauerring 7\n81737 Muenchen",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkuendigungsrecht bei Beitragserhohung.",
  },
  {
    id: "zurich",
    name: "Zurich Versicherung",
    category: "versicherung",
    address: "Zurich Gruppe Deutschland\nSolmsstrasse 27-37\n60486 Frankfurt am Main",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer unbedingt angeben.",
  },
  {
    id: "dkv",
    name: "DKV (Deutsche Krankenversicherung)",
    category: "versicherung",
    address: "DKV AG\n50594 Koeln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "PKV-Kuendigung: Nachweis der Anschlussversicherung erforderlich!",
  },
  {
    id: "lvm",
    name: "LVM Versicherung",
    category: "versicherung",
    address: "LVM Versicherung\nKolde-Ring 21\n48151 Muenster",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung ueber den Vertreter oder per Einschreiben.",
  },
  {
    id: "devk",
    name: "DEVK Versicherung",
    category: "versicherung",
    address: "DEVK Versicherungen\nRiehler Strasse 190\n50735 Koeln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkuendigungsrecht nach Schadensfall.",
  },
  {
    id: "wuerttembergische",
    name: "Wuerttembergische Versicherung",
    category: "versicherung",
    address: "Wuerttembergische Versicherung AG\n70163 Stuttgart",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer und Sparte angeben.",
  },
  {
    id: "gothaer",
    name: "Gothaer Versicherung",
    category: "versicherung",
    address: "Gothaer Allgemeine Versicherung AG\n50598 Koeln",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Per Einschreiben senden.",
  },
  {
    id: "signal-iduna",
    name: "SIGNAL IDUNA",
    category: "versicherung",
    address: "SIGNAL IDUNA Gruppe\nJoseph-Scherer-Strasse 3\n44139 Dortmund",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsnummer angeben.",
  },
  {
    id: "hdi",
    name: "HDI Versicherung",
    category: "versicherung",
    address: "HDI Versicherung AG\n30659 Hannover",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Einschreiben empfohlen.",
  },
  {
    id: "nuernberger",
    name: "Nuernberger Versicherung",
    category: "versicherung",
    address: "Nuernberger Versicherung AG\n90334 Nuernberg",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertrag und Versicherungsscheinnummer angeben.",
  },
  {
    id: "r-und-v",
    name: "R+V Versicherung",
    category: "versicherung",
    address: "R+V Allgemeine Versicherung AG\n65181 Wiesbaden",
    kuendigungsfrist: "3 Monate zum Versicherungsjahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Genossenschaftliche Versicherung. Berater kontaktieren empfohlen.",
  },
  {
    id: "barmer",
    name: "BARMER (Krankenkasse)",
    category: "versicherung",
    address: "BARMER\n42271 Wuppertal",
    kuendigungsfrist: "2 Monate zum Monatsende (nach 12 Monaten Bindung)",
    mindestlaufzeit: "18 Monate bei Neuwahl",
    kuendigungsart: ["Schriftlich"],
    hinweise: "GKV-Wechsel: Neue Kasse vor Kuendigung waehlen! Sonderkuendigung bei Zusatzbeitragserhoehung.",
  },
  {
    id: "tk",
    name: "Techniker Krankenkasse (TK)",
    category: "versicherung",
    address: "Techniker Krankenkasse\n22291 Hamburg",
    kuendigungsfrist: "2 Monate zum Monatsende",
    mindestlaufzeit: "18 Monate bei Neuwahl",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Mitgliedschaft bei der neuen Kasse nachweisen!",
  },
  {
    id: "aok",
    name: "AOK",
    category: "versicherung",
    address: "(Adresse Ihrer regionalen AOK eintragen)",
    kuendigungsfrist: "2 Monate zum Monatsende",
    mindestlaufzeit: "18 Monate bei Neuwahl",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Regionale AOK-Adressen variieren. GKV-Wechsel: Nachweis der neuen Kasse beilegen.",
  },
  {
    id: "dak",
    name: "DAK-Gesundheit",
    category: "versicherung",
    address: "DAK-Gesundheit\n22097 Hamburg",
    kuendigungsfrist: "2 Monate zum Monatsende",
    mindestlaufzeit: "18 Monate bei Neuwahl",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Sonderkuendigungsrecht bei Zusatzbeitragserhoehung.",
  },

  // ========== ENERGIE ==========
  {
    id: "eon",
    name: "E.ON Energie",
    category: "energie",
    address: "E.ON Energie Deutschland GmbH\n80335 Muenchen",
    kuendigungsfrist: "1 Monat (Grundversorgung) / vertragsabhaengig",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "In der Grundversorgung: 2 Wochen Kuendigungsfrist.",
  },
  {
    id: "vattenfall",
    name: "Vattenfall",
    category: "energie",
    address: "Vattenfall Europe Sales GmbH\n10115 Berlin",
    kuendigungsfrist: "1 Monat (Grundversorgung) / vertragsabhaengig",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorgung: 2 Wochen Frist. Bei Umzug Sonderkuendigungsrecht.",
  },
  {
    id: "rwe",
    name: "RWE / innogy",
    category: "energie",
    address: "RWE AG\nHuyssenallee 2\n45128 Essen",
    kuendigungsfrist: "Vertragsabhaengig",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Vertragsbedingungen im Einzelfall pruefen.",
  },
  {
    id: "enbw",
    name: "EnBW",
    category: "energie",
    address: "EnBW Energie Baden-Wuerttemberg AG\n76131 Karlsruhe",
    kuendigungsfrist: "1 Monat (Grundversorgung)",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorgung jederzeit mit 2 Wochen Frist kuendbar.",
  },
  {
    id: "stadtwerke-muenchen",
    name: "Stadtwerke Muenchen (SWM)",
    category: "energie",
    address: "Stadtwerke Muenchen GmbH\n80287 Muenchen",
    kuendigungsfrist: "1 Monat (Grundversorgung)",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Grundversorgung: 2 Wochen Frist.",
  },
  {
    id: "yello",
    name: "Yello Strom",
    category: "energie",
    address: "Yello Strom GmbH\n50823 Koeln",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Tochter der EnBW.",
  },
  {
    id: "eprimo",
    name: "eprimo",
    category: "energie",
    address: "eprimo GmbH\n63263 Neu-Isenburg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Tochterunternehmen von E.ON. Online-Kuendigung moeglich.",
  },
  {
    id: "lichtblick",
    name: "LichtBlick",
    category: "energie",
    address: "LichtBlick SE\nZirkusweg 6\n20359 Hamburg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "Keine (monatlich kuendbar)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Oekostrom-Anbieter. Monatlich kuendbar.",
  },
  {
    id: "naturstrom",
    name: "NATURSTROM",
    category: "energie",
    address: "NATURSTROM AG\n40237 Duesseldorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "Keine (monatlich kuendbar)",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Oekostrom-Anbieter.",
  },
  {
    id: "envia-m",
    name: "enviaM",
    category: "energie",
    address: "envia Mitteldeutsche Energie AG\n09111 Chemnitz",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "Vertragsabhaengig",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Regionalversorger fuer Mitteldeutschland.",
  },

  // ========== FITNESS ==========
  {
    id: "mcfit",
    name: "McFIT",
    category: "fitness",
    address: "RSG Group GmbH\nFranz-Ehrlich-Strasse 5\n12489 Berlin",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online-Kuendigung ueber Mitgliederbereich. Einschreiben empfohlen.",
  },
  {
    id: "fitx",
    name: "FitX",
    category: "fitness",
    address: "FitX Deutschland GmbH\nUeberseering 33b\n22297 Hamburg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung per Einschreiben an die Studioadresse senden.",
  },
  {
    id: "fitness-first",
    name: "Fitness First",
    category: "fitness",
    address: "Fitness First Germany GmbH\n60329 Frankfurt am Main",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung muss vor Ort oder schriftlich erfolgen.",
  },
  {
    id: "clever-fit",
    name: "clever fit",
    category: "fitness",
    address: "clever fit GmbH\n86199 Augsburg",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung an das jeweilige Studio senden.",
  },
  {
    id: "urban-sports",
    name: "Urban Sports Club",
    category: "fitness",
    address: "Urban Sports Club\nKoepenicker Str. 9\n10997 Berlin",
    kuendigungsfrist: "1 Monat",
    mindestlaufzeit: "Keine (monatlich kuendbar)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber die App oder das Online-Konto.",
  },
  {
    id: "john-reed",
    name: "John Reed Fitness",
    category: "fitness",
    address: "RSG Group GmbH\nFranz-Ehrlich-Strasse 5\n12489 Berlin",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Gehoert zur RSG Group (wie McFIT). Einschreiben empfohlen.",
  },
  {
    id: "bodystreet",
    name: "Bodystreet (EMS-Training)",
    category: "fitness",
    address: "(Adresse Ihres lokalen Bodystreet Studios eintragen)",
    kuendigungsfrist: "Vertragsabhaengig (meist 3 Monate)",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "EMS-Studio. Kuendigung direkt an das Franchise-Studio senden.",
  },
  {
    id: "kieser-training",
    name: "Kieser Training",
    category: "fitness",
    address: "(Adresse Ihres lokalen Kieser Studios eintragen)",
    kuendigungsfrist: "3 Monate zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung an die jeweilige Studioadresse.",
  },

  // ========== STREAMING ==========
  {
    id: "netflix",
    name: "Netflix",
    category: "streaming",
    address: "Netflix International B.V.\nKarperstraat 8-10\n1075 KZ Amsterdam, Niederlande",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung direkt ueber die Netflix-Kontoeinstellungen.",
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "streaming",
    address: "Spotify AB\nRegeringsgatan 19\n111 53 Stockholm, Schweden",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber spotify.com/account.",
  },
  {
    id: "amazon-prime",
    name: "Amazon Prime",
    category: "streaming",
    address: "Amazon Europe Core S.a r.l.\n38 avenue John F. Kennedy\nL-1855 Luxemburg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Amazon-Kontoeinstellungen. Anteilige Erstattung moeglich.",
  },
  {
    id: "dazn",
    name: "DAZN",
    category: "streaming",
    address: "DAZN Limited\n12 Hammersmith Grove\nLondon W6 7AP, UK",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Abhaengig vom gewaehlten Abo",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber die DAZN-App oder Webseite.",
  },
  {
    id: "sky",
    name: "Sky Deutschland",
    category: "streaming",
    address: "Sky Deutschland Fernsehen GmbH & Co. KG\nMedienallee 26\n85774 Unterfoehring",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "12 Monate",
    kuendigungsart: ["Schriftlich", "Online", "Telefon"],
    hinweise: "Telefon: 089 99 72 79 00. Per Brief oder Fax.",
  },
  {
    id: "disney-plus",
    name: "Disney+",
    category: "streaming",
    address: "The Walt Disney Company (Benelux) B.V.\nDe Passage 144\n1101 AX Amsterdam, Niederlande",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber die Disney+ Kontoeinstellungen.",
  },
  {
    id: "apple-tv-plus",
    name: "Apple TV+",
    category: "streaming",
    address: "Apple Distribution International Ltd.\nHollyhill Industrial Estate\nCork, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Apple-ID Einstellungen.",
  },
  {
    id: "wow-sky",
    name: "WOW (ehem. Sky Ticket)",
    category: "streaming",
    address: "Sky Deutschland Fernsehen GmbH & Co. KG\n85774 Unterfoehring",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber wow.sky.de.",
  },
  {
    id: "rtlplus",
    name: "RTL+",
    category: "streaming",
    address: "RTL interactive GmbH\nPicassoplatz 1\n50679 Koeln",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber rtlplus.de Kontoeinstellungen.",
  },
  {
    id: "joyn",
    name: "Joyn PLUS+",
    category: "streaming",
    address: "Joyn GmbH\n80335 Muenchen",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber das Joyn-Konto.",
  },
  {
    id: "audible",
    name: "Audible",
    category: "streaming",
    address: "Audible GmbH\nLehrter Strasse 57\n10557 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber audible.de Kontoeinstellungen. Guthaben bleibt erhalten.",
  },
  {
    id: "deezer",
    name: "Deezer",
    category: "streaming",
    address: "Deezer SA\n24 rue de Calais\n75009 Paris, Frankreich",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber deezer.com Kontoeinstellungen.",
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    category: "streaming",
    address: "Google Ireland Ltd.\nGordon House\nBarrow Street, Dublin 4, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Google-Kontoeinstellungen.",
  },

  // ========== BANK & FINANZEN ==========
  {
    id: "sparkasse",
    name: "Sparkasse",
    category: "bank",
    address: "(Adresse Ihrer lokalen Sparkasse eintragen)",
    kuendigungsfrist: "Jederzeit (Girokonto)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Girokonto jederzeit kuendbar. Alle Dauerauftraege vorher aendern!",
  },
  {
    id: "dkb",
    name: "DKB (Deutsche Kreditbank)",
    category: "bank",
    address: "Deutsche Kreditbank AG\nTaubenstrasse 7-9\n10117 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Konto vorher auf 0 bringen. Neue Bankverbindung fuer Dauerauftraege einrichten.",
  },
  {
    id: "ing",
    name: "ING",
    category: "bank",
    address: "ING-DiBa AG\n60628 Frankfurt am Main",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Kuendigung ueber das Internetbanking moeglich.",
  },
  {
    id: "commerzbank",
    name: "Commerzbank",
    category: "bank",
    address: "Commerzbank AG\n60261 Frankfurt am Main",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigungsschreiben per Einschreiben senden.",
  },
  {
    id: "n26",
    name: "N26",
    category: "bank",
    address: "N26 Bank GmbH\nVoltairestrasse 8\n10179 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Kuendigung direkt ueber die N26-App. E-Mail: support@n26.com",
  },
  {
    id: "deutsche-bank",
    name: "Deutsche Bank",
    category: "bank",
    address: "Deutsche Bank AG\n60262 Frankfurt am Main",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung schriftlich an die kontofuehrende Filiale.",
  },
  {
    id: "postbank",
    name: "Postbank",
    category: "bank",
    address: "Deutsche Bank AG (Postbank)\n53113 Bonn",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Seit 2023 Teil der Deutschen Bank.",
  },
  {
    id: "comdirect",
    name: "comdirect",
    category: "bank",
    address: "comdirect (Commerzbank AG)\n25449 Quickborn",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Gehoert zur Commerzbank. Online-Kuendigung moeglich.",
  },
  {
    id: "targobank",
    name: "TARGOBANK",
    category: "bank",
    address: "TARGOBANK AG\n40210 Duesseldorf",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Girokonto jederzeit kuendbar. Kreditvertraege haben separate Fristen.",
  },
  {
    id: "volksbank",
    name: "Volksbank / Raiffeisenbank",
    category: "bank",
    address: "(Adresse Ihrer lokalen Volksbank eintragen)",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Genossenschaftsbank. Kuendigung an die lokale Filiale.",
  },
  {
    id: "consorsbank",
    name: "Consorsbank",
    category: "bank",
    address: "BNP Paribas S.A. Niederlassung Deutschland\n90318 Nuernberg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Online- oder schriftliche Kuendigung.",
  },
  {
    id: "santander",
    name: "Santander Consumer Bank",
    category: "bank",
    address: "Santander Consumer Bank AG\n41061 Moenchengladbach",
    kuendigungsfrist: "Jederzeit (Konto) / Vertragsabhaengig (Kredit)",
    mindestlaufzeit: "Keine (Konto)",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kreditvertraege: Sondertilgungsrecht pruefen.",
  },
  {
    id: "scalable-capital",
    name: "Scalable Capital",
    category: "bank",
    address: "Scalable Capital GmbH\nSeitzstrasse 8e\n80538 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Depot-Kuendigung ueber die App. Alle Wertpapiere vorher uebertragen oder verkaufen.",
  },
  {
    id: "trade-republic",
    name: "Trade Republic",
    category: "bank",
    address: "Trade Republic Bank GmbH\nKastanienallee 32\n10435 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Depot-Kuendigung ueber die App. Guthaben vorher ueberweisen.",
  },

  // ========== INTERNET & DSL ==========
  {
    id: "unitymedia",
    name: "Unitymedia / Vodafone Kabel",
    category: "internet",
    address: "Vodafone GmbH\nKundenbetreuung\n40549 Duesseldorf",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Nach Uebernahme durch Vodafone: Kuendigung an Vodafone richten.",
  },
  {
    id: "pyur",
    name: "PYUR / Tele Columbus",
    category: "internet",
    address: "Tele Columbus AG\n10587 Berlin",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung per Einschreiben empfohlen.",
  },
  {
    id: "easybell",
    name: "easybell",
    category: "internet",
    address: "easybell GmbH\nErkelenzdamm 61-63\n10999 Berlin",
    kuendigungsfrist: "1 Monat",
    mindestlaufzeit: "Keine (monatlich kuendbar)",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Monatlich kuendbar. Kuendigung ueber das Kundenportal.",
  },
  {
    id: "m-net",
    name: "M-net",
    category: "internet",
    address: "M-net Telekommunikations GmbH\n80339 Muenchen",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Regionalanbieter in Bayern.",
  },
  {
    id: "netcologne",
    name: "NetCologne",
    category: "internet",
    address: "NetCologne GmbH\n50667 Koeln",
    kuendigungsfrist: "1 Monat zum Vertragsende",
    mindestlaufzeit: "24 Monate",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Regionalanbieter im Raum Koeln.",
  },
  {
    id: "waipu-tv",
    name: "waipu.tv",
    category: "internet",
    address: "EXARING AG\nMuenzstrasse 18\n10178 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber waipu.tv Kontoeinstellungen.",
  },

  // ========== VERLAG & ZEITSCHRIFTEN ==========
  {
    id: "spiegel",
    name: "Der Spiegel",
    category: "verlag",
    address: "DER SPIEGEL GmbH & Co. KG\nAbo-Service\n20637 Hamburg",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "E-Mail: abo@spiegel.de. Kundennummer angeben.",
  },
  {
    id: "zeit",
    name: "Die Zeit",
    category: "verlag",
    address: "Zeitverlag Gerd Bucerius GmbH & Co. KG\nAbo-Service\n20080 Hamburg",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "E-Mail: abo@zeit.de",
  },
  {
    id: "sueddeutsche",
    name: "Sueddeutsche Zeitung",
    category: "verlag",
    address: "Sueddeutsche Zeitung GmbH\nAbo-Service\n80289 Muenchen",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kuendigung per Brief oder Fax an den Abo-Service.",
  },
  {
    id: "bild",
    name: "BILD / BILDplus",
    category: "verlag",
    address: "Axel Springer SE\nAbo-Service\n20350 Hamburg",
    kuendigungsfrist: "Jederzeit zum Monatsende (Digital)",
    mindestlaufzeit: "Keine (Digital-Abo)",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Digital-Abo online kuendbar. Print-Abo: Fristen pruefen.",
  },
  {
    id: "faz",
    name: "Frankfurter Allgemeine Zeitung (FAZ)",
    category: "verlag",
    address: "Frankfurter Allgemeine Zeitung GmbH\nAbo-Service\n60267 Frankfurt am Main",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "E-Mail: abo-service@faz.de",
  },
  {
    id: "welt",
    name: "Die Welt / WELTplus",
    category: "verlag",
    address: "Axel Springer SE\nAbo-Service\n10888 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende (Digital)",
    mindestlaufzeit: "Keine (Digital-Abo)",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Digital-Abo ueber Kontoeinstellungen kuendbar.",
  },
  {
    id: "focus",
    name: "FOCUS",
    category: "verlag",
    address: "BurdaVerlag GmbH\nAbo-Service\n77649 Offenburg",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Kundennummer im Schreiben angeben.",
  },
  {
    id: "stern",
    name: "stern",
    category: "verlag",
    address: "Gruner + Jahr GmbH\nAbo-Service\n20637 Hamburg",
    kuendigungsfrist: "6 Wochen zum Ende des Bezugszeitraums",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Gehoert zur RTL-Gruppe.",
  },
  {
    id: "handelsblatt",
    name: "Handelsblatt",
    category: "verlag",
    address: "Handelsblatt GmbH\nAbo-Service\n40210 Duesseldorf",
    kuendigungsfrist: "4 Wochen zum Monatsende",
    mindestlaufzeit: "Abhaengig vom Abo",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "E-Mail: leserservice@handelsblatt.com",
  },

  // ========== MITGLIEDSCHAFT & VEREIN ==========
  {
    id: "adac",
    name: "ADAC",
    category: "mitgliedschaft",
    address: "ADAC e.V.\n81360 Muenchen",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Mitgliedschaft verlaengert sich automatisch. Einschreiben empfohlen.",
  },
  {
    id: "gewerkschaft-verdi",
    name: "ver.di Gewerkschaft",
    category: "mitgliedschaft",
    address: "ver.di\nPaula-Thiede-Ufer 10\n10179 Berlin",
    kuendigungsfrist: "3 Monate zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Austritt zum Ende eines Kalendervierteljahres.",
  },
  {
    id: "bahncard",
    name: "BahnCard (Deutsche Bahn)",
    category: "mitgliedschaft",
    address: "Deutsche Bahn AG\nBahnCard-Service\n60643 Frankfurt am Main",
    kuendigungsfrist: "6 Wochen vor Ablauf",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich", "Online", "Telefon"],
    hinweise: "Online-Kuendigung ueber bahn.de. Telefon: 030 2970.",
  },
  {
    id: "ig-metall",
    name: "IG Metall",
    category: "mitgliedschaft",
    address: "IG Metall Vorstand\nWilhelm-Leuschner-Strasse 79\n60329 Frankfurt am Main",
    kuendigungsfrist: "3 Monate zum Quartalsende",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Austritt schriftlich an die Verwaltungsstelle.",
  },
  {
    id: "gez-rundfunkbeitrag",
    name: "Rundfunkbeitrag (GEZ)",
    category: "mitgliedschaft",
    address: "ARD ZDF Deutschlandradio Beitragsservice\n50656 Koeln",
    kuendigungsfrist: "Abmeldung bei Abmeldung/Umzug",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Abmeldung nur bei Abmeldung der Wohnung, Umzug ins Ausland o.ae. Befreiung beantragen bei geringem Einkommen.",
  },
  {
    id: "amazon-prime-member",
    name: "Amazon Prime (Mitgliedschaft)",
    category: "mitgliedschaft",
    address: "Amazon Europe Core S.a r.l.\n38 avenue John F. Kennedy\nL-1855 Luxemburg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Amazon-Konto. Anteilige Erstattung bei Jahresabo moeglich.",
  },
  {
    id: "automobilclub-ace",
    name: "ACE Auto Club Europa",
    category: "mitgliedschaft",
    address: "ACE Auto Club Europa e.V.\n70372 Stuttgart",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Alternative zum ADAC.",
  },
  {
    id: "avc",
    name: "AvD (Automobilclub von Deutschland)",
    category: "mitgliedschaft",
    address: "Automobilclub von Deutschland e.V.\n60487 Frankfurt am Main",
    kuendigungsfrist: "3 Monate zum Jahresende",
    mindestlaufzeit: "1 Jahr",
    kuendigungsart: ["Schriftlich"],
    hinweise: "Einschreiben empfohlen.",
  },

  // ========== SONSTIGES ==========
  {
    id: "check24",
    name: "CHECK24",
    category: "sonstiges",
    address: "CHECK24 Vergleichsportal GmbH\nErika-Mann-Str. 62-66\n80636 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto jederzeit loeschbar. E-Mail: kundenservice@check24.de",
  },
  {
    id: "parship",
    name: "Parship",
    category: "sonstiges",
    address: "PE Digital GmbH\nSpeersort 10\n20095 Hamburg",
    kuendigungsfrist: "12 Wochen zum Vertragsende",
    mindestlaufzeit: "6 Monate",
    kuendigungsart: ["Schriftlich", "Fax"],
    hinweise: "Widerruf innerhalb von 14 Tagen. Danach: 12 Wochen Frist.",
  },
  {
    id: "elitepartner",
    name: "ElitePartner",
    category: "sonstiges",
    address: "PE Digital GmbH\nSpeersort 10\n20095 Hamburg",
    kuendigungsfrist: "12 Wochen zum Vertragsende",
    mindestlaufzeit: "6 Monate",
    kuendigungsart: ["Schriftlich", "Fax"],
    hinweise: "Gleiche Frist wie Parship. Widerruf 14 Tage moeglich.",
  },
  {
    id: "verivox",
    name: "Verivox",
    category: "sonstiges",
    address: "Verivox GmbH\n69115 Heidelberg",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Vergleichsportal. Konto jederzeit loeschbar.",
  },
  {
    id: "schufa",
    name: "SCHUFA (meineSCHUFA)",
    category: "sonstiges",
    address: "SCHUFA Holding AG\nKormoranweg 5\n65201 Wiesbaden",
    kuendigungsfrist: "Abhaengig vom Paket",
    mindestlaufzeit: "Abhaengig vom Paket",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "meineSCHUFA-Paket online kuendbar.",
  },
  {
    id: "payback",
    name: "PAYBACK",
    category: "sonstiges",
    address: "PAYBACK GmbH\nTheresienhöhe 12\n80339 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "E-Mail"],
    hinweise: "Punkte vor Kuendigung einloesen! E-Mail: service@payback.de",
  },
  {
    id: "deutschlandcard",
    name: "DeutschlandCard",
    category: "sonstiges",
    address: "DeutschlandCard GmbH\n81671 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Punkte vor Kuendigung einloesen.",
  },
  {
    id: "immoscout24",
    name: "ImmobilienScout24",
    category: "sonstiges",
    address: "Immobilien Scout GmbH\nAndreasstrasse 10\n10243 Berlin",
    kuendigungsfrist: "Jederzeit zum Monatsende (Premium)",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "MieterPlus/ImmobilienScout24 Premium kuendbar ueber das Konto.",
  },
  {
    id: "ebay-kleinanzeigen",
    name: "Kleinanzeigen (ehem. eBay)",
    category: "sonstiges",
    address: "Kleinanzeigen GmbH\n10969 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kostenloses Konto. Bezahlte Dienste online kuendbar.",
  },
  {
    id: "lieferando",
    name: "Lieferando",
    category: "sonstiges",
    address: "Takeaway.com Group B.V.\nOosterdoksstraat 80\n1011 DK Amsterdam, Niederlande",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto loeschbar ueber Kontoeinstellungen.",
  },
  {
    id: "hellofresh",
    name: "HelloFresh",
    category: "sonstiges",
    address: "HelloFresh SE\nSaarbruecker Strasse 37a\n10405 Berlin",
    kuendigungsfrist: "Jederzeit (vor Bestellfrist der naechsten Woche)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Abo pausieren oder kuendigen ueber die App/Webseite.",
  },
  {
    id: "marley-spoon",
    name: "Marley Spoon",
    category: "sonstiges",
    address: "Marley Spoon GmbH\n10999 Berlin",
    kuendigungsfrist: "Jederzeit (vor Bestellfrist)",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kochbox-Abo jederzeit pausierbar/kuendbar.",
  },
  {
    id: "mydays",
    name: "mydays",
    category: "sonstiges",
    address: "mydays GmbH\n81541 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["E-Mail"],
    hinweise: "Konto loeschbar per E-Mail an den Kundenservice.",
  },
  {
    id: "tinder",
    name: "Tinder",
    category: "sonstiges",
    address: "Match Group, LLC\n8750 N. Central Expressway\nDallas, TX 75231, USA",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber App Store / Google Play oder tinder.com.",
  },
  {
    id: "bumble",
    name: "Bumble",
    category: "sonstiges",
    address: "Bumble Inc.\nAustin, TX, USA",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber App Store / Google Play.",
  },
  {
    id: "mcdonalds-app",
    name: "McDonald's App (MyMcDonald's Rewards)",
    category: "sonstiges",
    address: "McDonald's Deutschland LLC\n80339 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Konto loeschbar ueber App-Einstellungen.",
  },
  {
    id: "flixbus",
    name: "FlixBus / Flixtrain",
    category: "sonstiges",
    address: "FlixMobility GmbH\nFriedenheimerbruecke 16\n80639 Muenchen",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto loeschbar. Einzelbuchungen stornierbar je nach Tarif.",
  },
  {
    id: "sixt",
    name: "SIXT (Abo/Flatrate)",
    category: "sonstiges",
    address: "Sixt SE\nZugspitzstrasse 1\n82049 Pullach",
    kuendigungsfrist: "Vertragsabhaengig",
    mindestlaufzeit: "Abhaengig vom Abo-Modell",
    kuendigungsart: ["Schriftlich", "Online"],
    hinweise: "Auto-Abo Kuendigungsfristen im Vertrag pruefen.",
  },
  {
    id: "miles",
    name: "MILES Carsharing",
    category: "sonstiges",
    address: "MILES Mobility GmbH\n10997 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online", "E-Mail"],
    hinweise: "Konto loeschbar ueber die App.",
  },
  {
    id: "share-now",
    name: "SHARE NOW",
    category: "sonstiges",
    address: "SHARE NOW GmbH\n10117 Berlin",
    kuendigungsfrist: "Jederzeit",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Konto kuendbar ueber die App.",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    category: "sonstiges",
    address: "Dropbox International Unlimited Company\nDublin, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber dropbox.com Kontoeinstellungen.",
  },
  {
    id: "icloud",
    name: "iCloud+ (Apple)",
    category: "sonstiges",
    address: "Apple Distribution International Ltd.\nCork, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Apple-ID Einstellungen.",
  },
  {
    id: "microsoft365",
    name: "Microsoft 365",
    category: "sonstiges",
    address: "Microsoft Ireland Operations Ltd.\nDublin, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber account.microsoft.com.",
  },
  {
    id: "google-one",
    name: "Google One",
    category: "sonstiges",
    address: "Google Ireland Ltd.\nDublin 4, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber Google-Kontoeinstellungen.",
  },
  {
    id: "adobe-cc",
    name: "Adobe Creative Cloud",
    category: "sonstiges",
    address: "Adobe Systems Software Ireland Ltd.\nDublin, Irland",
    kuendigungsfrist: "14 Tage Widerruf / Vorzeitige Kuendigung mit Gebuehr",
    mindestlaufzeit: "12 Monate (Jahresabo)",
    kuendigungsart: ["Online"],
    hinweise: "Vorzeitige Kuendigung des Jahresabos: 50% der Restlaufzeit als Gebuehr.",
  },
  {
    id: "linkedin-premium",
    name: "LinkedIn Premium",
    category: "sonstiges",
    address: "LinkedIn Ireland Unlimited Company\nDublin, Irland",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber linkedin.com Kontoeinstellungen.",
  },
  {
    id: "xing-premium",
    name: "XING Premium",
    category: "sonstiges",
    address: "New Work SE\nDammtorstrasse 30\n20354 Hamburg",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine (Monatsabo) / 12 Monate (Jahresabo)",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber xing.com Kontoeinstellungen.",
  },
  {
    id: "chatgpt-plus",
    name: "ChatGPT Plus (OpenAI)",
    category: "sonstiges",
    address: "OpenAI LLC\nSan Francisco, CA, USA",
    kuendigungsfrist: "Jederzeit zum Ende des Abrechnungszeitraums",
    mindestlaufzeit: "Keine",
    kuendigungsart: ["Online"],
    hinweise: "Kuendigung ueber chat.openai.com Kontoeinstellungen.",
  },
]
